# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.grpc import user_pb2 as api_dot_grpc_dot_user__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api/grpc/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """用户服务 - 提供用户账户管理和信息查询功能
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/suoke.user.UserService/CreateUser',
                request_serializer=api_dot_grpc_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/suoke.user.UserService/GetUser',
                request_serializer=api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/suoke.user.UserService/UpdateUser',
                request_serializer=api_dot_grpc_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/suoke.user.UserService/DeleteUser',
                request_serializer=api_dot_grpc_dot_user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/suoke.user.UserService/ListUsers',
                request_serializer=api_dot_grpc_dot_user__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.GetUserHealthSummary = channel.unary_unary(
                '/suoke.user.UserService/GetUserHealthSummary',
                request_serializer=api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.HealthSummaryResponse.FromString,
                _registered_method=True)
        self.UpdateUserHealthSummary = channel.unary_unary(
                '/suoke.user.UserService/UpdateUserHealthSummary',
                request_serializer=api_dot_grpc_dot_user__pb2.UpdateHealthSummaryRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.HealthSummaryResponse.FromString,
                _registered_method=True)
        self.BindUserDevice = channel.unary_unary(
                '/suoke.user.UserService/BindUserDevice',
                request_serializer=api_dot_grpc_dot_user__pb2.BindDeviceRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.DeviceResponse.FromString,
                _registered_method=True)
        self.UnbindUserDevice = channel.unary_unary(
                '/suoke.user.UserService/UnbindUserDevice',
                request_serializer=api_dot_grpc_dot_user__pb2.UnbindDeviceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUserDevices = channel.unary_unary(
                '/suoke.user.UserService/GetUserDevices',
                request_serializer=api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.GetUserPreferences = channel.unary_unary(
                '/suoke.user.UserService/GetUserPreferences',
                request_serializer=api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.UserPreferencesResponse.FromString,
                _registered_method=True)
        self.UpdateUserPreferences = channel.unary_unary(
                '/suoke.user.UserService/UpdateUserPreferences',
                request_serializer=api_dot_grpc_dot_user__pb2.UpdatePreferencesRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.UserPreferencesResponse.FromString,
                _registered_method=True)
        self.VerifyUserIdentity = channel.unary_unary(
                '/suoke.user.UserService/VerifyUserIdentity',
                request_serializer=api_dot_grpc_dot_user__pb2.VerifyIdentityRequest.SerializeToString,
                response_deserializer=api_dot_grpc_dot_user__pb2.VerifyIdentityResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """用户服务 - 提供用户账户管理和信息查询功能
    """

    def CreateUser(self, request, context):
        """用户账户操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserHealthSummary(self, request, context):
        """用户健康数据摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserHealthSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindUserDevice(self, request, context):
        """用户设备绑定管理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnbindUserDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPreferences(self, request, context):
        """用户偏好设置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserIdentity(self, request, context):
        """用户认证
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=api_dot_grpc_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=api_dot_grpc_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=api_dot_grpc_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=api_dot_grpc_dot_user__pb2.DeleteUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=api_dot_grpc_dot_user__pb2.ListUsersRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.ListUsersResponse.SerializeToString,
            ),
            'GetUserHealthSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserHealthSummary,
                    request_deserializer=api_dot_grpc_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.HealthSummaryResponse.SerializeToString,
            ),
            'UpdateUserHealthSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserHealthSummary,
                    request_deserializer=api_dot_grpc_dot_user__pb2.UpdateHealthSummaryRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.HealthSummaryResponse.SerializeToString,
            ),
            'BindUserDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.BindUserDevice,
                    request_deserializer=api_dot_grpc_dot_user__pb2.BindDeviceRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.DeviceResponse.SerializeToString,
            ),
            'UnbindUserDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UnbindUserDevice,
                    request_deserializer=api_dot_grpc_dot_user__pb2.UnbindDeviceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUserDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDevices,
                    request_deserializer=api_dot_grpc_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.ListDevicesResponse.SerializeToString,
            ),
            'GetUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPreferences,
                    request_deserializer=api_dot_grpc_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.UserPreferencesResponse.SerializeToString,
            ),
            'UpdateUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserPreferences,
                    request_deserializer=api_dot_grpc_dot_user__pb2.UpdatePreferencesRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.UserPreferencesResponse.SerializeToString,
            ),
            'VerifyUserIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserIdentity,
                    request_deserializer=api_dot_grpc_dot_user__pb2.VerifyIdentityRequest.FromString,
                    response_serializer=api_dot_grpc_dot_user__pb2.VerifyIdentityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suoke.user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('suoke.user.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """用户服务 - 提供用户账户管理和信息查询功能
    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/CreateUser',
            api_dot_grpc_dot_user__pb2.CreateUserRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/GetUser',
            api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/UpdateUser',
            api_dot_grpc_dot_user__pb2.UpdateUserRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/DeleteUser',
            api_dot_grpc_dot_user__pb2.DeleteUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/ListUsers',
            api_dot_grpc_dot_user__pb2.ListUsersRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserHealthSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/GetUserHealthSummary',
            api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.HealthSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserHealthSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/UpdateUserHealthSummary',
            api_dot_grpc_dot_user__pb2.UpdateHealthSummaryRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.HealthSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindUserDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/BindUserDevice',
            api_dot_grpc_dot_user__pb2.BindDeviceRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.DeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnbindUserDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/UnbindUserDevice',
            api_dot_grpc_dot_user__pb2.UnbindDeviceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/GetUserDevices',
            api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/GetUserPreferences',
            api_dot_grpc_dot_user__pb2.GetUserRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.UserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/UpdateUserPreferences',
            api_dot_grpc_dot_user__pb2.UpdatePreferencesRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.UserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUserIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suoke.user.UserService/VerifyUserIdentity',
            api_dot_grpc_dot_user__pb2.VerifyIdentityRequest.SerializeToString,
            api_dot_grpc_dot_user__pb2.VerifyIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
