apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke

bases:
  - ../../base

patchesStrategicMerge:
  - ../../patches/prod-overlay.yaml
  - ../../patches/resources-prod-patch.yaml
  - ../../patches/node-selector-patch.yaml

configMapGenerator:
  - name: four-diagnosis-coordinator-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - OTEL_LOG_LEVEL=info
      - ENV_TYPE=production

images:
  - name: four-diagnosis-coordinator
    newName: suokelife/four-diagnosis-coordinator
    newTag: stable