apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: rag-service
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: ENABLE_CACHING
          value: "true"
        - name: CACHE_TTL
          value: "1800"
        - name: TELEMETRY_ENABLED
          value: "true"
        - name: TRACING_SAMPLE_RATE
          value: "1.0"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3 