apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke-dev

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
- name: rag-service-config
  behavior: merge
  literals:
  - ENV=development
  - VERSION=latest
  - LOG_LEVEL=debug
  - vector-db-host=milvus-service.suoke-dev.svc.cluster.local
  - redis-host=redis.suoke-dev.svc.cluster.local
  - otlp-endpoint=otel-collector.monitoring.svc.cluster.local:4317

namePrefix: dev-

images:
- name: ${DOCKER_REGISTRY}/suoke/rag-service
  newTag: latest

replicas:
- name: rag-service
  count: 1 