# Message Bus 服务生产环境配置

# 基本服务配置
environment: production
debug: false
enable_auth: true
max_message_size_bytes: 4194304  # 4MB

# 服务器配置
server:
  host: 0.0.0.0
  port: 50051
  max_workers: 30  # 生产环境增加工作线程

# Kafka配置
kafka:
  bootstrap_servers:
    - kafka-1.sokelife.internal:9092
    - kafka-2.sokelife.internal:9092
    - kafka-3.sokelife.internal:9092
  topic_prefix: sokelife-
  consumer_group_id: message-bus-service-prod
  auto_create_topics: false  # 生产环境中禁用自动创建主题
  security_protocol: SASL_SSL
  sasl_mechanism: PLAIN
  # 密码将通过环境变量注入: MB_KAFKA_SASL_PLAIN_USERNAME, MB_KAFKA_SASL_PLAIN_PASSWORD

# Redis配置
redis:
  host: redis.sokelife.internal
  port: 6379
  db: 0
  ssl: true
  # 密码将通过环境变量注入: MB_REDIS_PASSWORD

# 指标配置
metrics:
  enabled: true
  port: 9090

# 日志配置
logging:
  level: INFO
  format: json  # 生产环境使用JSON格式便于日志分析
  log_file: /var/log/sokelife/message_bus.log

# 消息配置
messages:
  default_ttl_hours: 72  # 生产环境增加消息保留时间
  retention_policy: archive  # 生产环境归档而非删除
  max_batch_size: 500  # 生产环境增加批处理大小

# 限流配置
rate_limiting:
  enabled: true
  max_requests_per_minute: 5000  # 生产环境提高限流阈值
  burst_size: 500

# 弹性配置
resilience:
  retry:
    max_attempts: 5  # 生产环境增加重试次数
    initial_backoff_ms: 200
    max_backoff_ms: 5000
    backoff_multiplier: 2.0
  circuit_breaker:
    failure_threshold: 10
    reset_timeout_ms: 60000
    half_open_requests: 2

# 安全配置
security:
  auth_service:
    url: https://auth.sokelife.internal/api/v1/validate
    timeout_ms: 5000
  jwt:
    public_key_path: "/etc/sokelife/certs/jwt/public.pem"
    issuer: sokelife-prod
    audience: message-bus
  tls:
    enabled: true
    cert_file: /etc/sokelife/certs/message-bus/server.crt
    key_file: /etc/sokelife/certs/message-bus/server.key
    ca_file: /etc/sokelife/certs/ca.crt 