global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "look-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["look-service:51051"]
    scrape_interval: 5s
    scrape_timeout: 4s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):\\d+"
        replacement: "$1"
      - source_labels: [job]
        target_label: service
      - target_label: component
        replacement: "望诊服务"

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):\\d+"
        replacement: "$1"
      - target_label: service
        replacement: "mongodb"
      - target_label: component
        replacement: "数据库"

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):\\d+"
        replacement: "$1"
      - target_label: service
        replacement: "redis"
      - target_label: component
        replacement: "缓存"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):\\d+"
        replacement: "$1"
      - target_label: service
        replacement: "node"
      - target_label: component
        replacement: "系统"

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):\\d+"
        replacement: "$1"
      - target_label: service
        replacement: "container"
      - target_label: component
        replacement: "容器" 