apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: accessibility-service
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  - port: 9090
    targetPort: 9090
    name: metrics
  type: ClusterIP 