apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |-
    service:
      name: accessibility-service
      version: 0.2.0
      host: 0.0.0.0
      port: 50051

    # 其他配置将通过kustomize合并 