[allowlist]
paths = ["docs/", "tests/"]

[[rules]]
id = "phone-number"
regex = '''\b1[3-9][0-9]{9}\b'''

[[rules]]
id = "id-card"
regex = '''\b\d{6}(19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])\d{3}[0-9Xx]\b'''

[[rules]]
id = "token"
regex = '''(?i)(token|secret|password|api[_-]?key)["'=:\s]+[a-z0-9\-_.]{8,}'''

[[rules]]
id = "private-key"
regex = '''-----BEGIN(.*?)PRIVATE KEY-----''' 