include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - prefer_const_constructors
    - use_super_parameters

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore
