targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
          prefer_relative_imports: true
          include_paths:
            - lib/app/presentation/pages/**
      injectable_builder:injectable_builder:
        enabled: true
        generate_for:
          - lib/**.dart
      json_serializable:json_serializable:
        enabled: true
        generate_for:
          - lib/**.dart
      retrofit_generator:
        options:
          dio_client_name: "Dio"
          generate_error_logger: true 