global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'suoke_app'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'llm_service'
    static_configs:
      - targets: ['llm_service:5000'] 