name: suoke_app
description: SuoKe Life App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  get_storage: ^2.1.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  flutter_local_notifications: ^16.3.2
  encrypt: ^5.0.3
  logger: ^2.0.2
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^9.0.0
  timeago: ^3.6.1
  record: ^5.0.4
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  sqflite_common_ffi: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_avatar.png
    - assets/images/xiaoai_avatar.png
    - assets/images/laoke_avatar.png
    - assets/images/xiaoke_avatar.png
    - assets/icons/
    - assets/animations/
