apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: accessibility-service
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ENABLE_PROFILING
          value: "true" 