apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - DEBUG=true

commonLabels:
  environment: development 