apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke

bases:
  - ../../base

patchesStrategicMerge:
  - ../../patches/prod-overlay.yaml
  - ../../patches/resources-prod-patch.yaml
  - ../../patches/node-selector-patch.yaml
  - ../../patches/storage-class-patch.yaml

configMapGenerator:
  - name: inquiry-diagnosis-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - OTEL_LOG_LEVEL=info
      - AI_MODEL_VERSION=stable

images:
  - name: inquiry-diagnosis-service
    newName: suokelife/inquiry-diagnosis-service
    newTag: stable 