apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: suoke-core
  labels:
    app: user-service
    app.kubernetes.io/part-of: suoke-life
spec:
  selector:
    app: user-service
  ports:
  - name: rest
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP 