# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from time import time
from typing import List
import grpc
    from grpc._utilities import first_version_is_lower



GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    pass
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    pass
    _version_not_supported = True

if _version_not_supported:
    pass
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in constitution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please self.upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or self.downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

class ConstitutionServiceStub(object):
    pass
    """体质类型定义服务
    """

    def __init__(self, channel):
    pass
        """Constructor.

        Args:
    pass
            channel: A grpc.Channel.
        """
        self.GetConstitutionDefinition = channel.unary_unary(
                '/xiaoai_service.constitution.ConstitutionService/GetConstitutionDefinition',
                request_serializer=constitution__pb2.ConstitutionRequest.SerializeToString,
                response_deserializer=constitution__pb2.ConstitutionDefinition.FromString,
                _registered_method=True)
        self.CalculateConstitutionScore = channel.unary_unary(
                '/xiaoai_service.constitution.ConstitutionService/CalculateConstitutionScore',
                request_serializer=constitution__pb2.ConstitutionScoreRequest.SerializeToString,
                response_deserializer=constitution__pb2.ConstitutionScoreResponse.FromString,
                _registered_method=True)
        self.ListConstitutionTypes = channel.unary_unary(
                '/xiaoai_service.constitution.ConstitutionService/ListConstitutionTypes',
                request_serializer=constitution__pb2.ListTypesRequest.SerializeToString,
                response_deserializer=constitution__pb2.ListTypesResponse.FromString,
                _registered_method=True)

class ConstitutionServiceServicer(object):
    pass
    """体质类型定义服务
    """

    def GetConstitutionDefinition(self, request, context):
    pass
        """获取体质类型定义
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateConstitutionScore(self, request, context):
    pass
        """计算体质得分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConstitutionTypes(self, request, context):
    pass
        """获取所有体质类型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_ConstitutionServiceServicer_to_server(servicer, server):
    pass
    rpc_method_handlers = {
            'GetConstitutionDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConstitutionDefinition,
                    request_deserializer=constitution__pb2.ConstitutionRequest.FromString,
                    response_serializer=constitution__pb2.ConstitutionDefinition.SerializeToString),
            'CalculateConstitutionScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateConstitutionScore,
                    request_deserializer=constitution__pb2.ConstitutionScoreRequest.FromString,
                    response_serializer=constitution__pb2.ConstitutionScoreResponse.SerializeToString),
            'ListConstitutionTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConstitutionTypes,
                    request_deserializer=constitution__pb2.ListTypesRequest.FromString,
                    response_serializer=constitution__pb2.ListTypesResponse.SerializeToString)}
    generic_handler = grpc.method_handlers_generic_handler(
            'xiaoai_service.constitution.ConstitutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler))
    server.add_registered_method_handlers('xiaoai_service.constitution.ConstitutionService', rpc_method_handlers)

class ConstitutionService(object):
    pass
    """体质类型定义服务
    """

    @staticmethod
    def GetConstitutionDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoai_service.constitution.ConstitutionService/GetConstitutionDefinition',
            constitution__pb2.ConstitutionRequest.SerializeToString,
            constitution__pb2.ConstitutionDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)

    @staticmethod
    def CalculateConstitutionScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoai_service.constitution.ConstitutionService/CalculateConstitutionScore',
            constitution__pb2.ConstitutionScoreRequest.SerializeToString,
            constitution__pb2.ConstitutionScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)

    @staticmethod
    def ListConstitutionTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoai_service.constitution.ConstitutionService/ListConstitutionTypes',
            constitution__pb2.ListTypesRequest.SerializeToString,
            constitution__pb2.ListTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)
