"""
look_service_pb2_grpc - 索克生活项目模块
"""

    from grpc._utilities import first_version_is_lower
from time import time
import grpc

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""




GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    pass
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    pass
    _version_not_supported = True

if _version_not_supported:
    pass
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in look_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please self.upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or self.downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

class LookServiceStub(object):
    pass
    """望诊服务 - 负责舌象、面色、形体等图像分析
    """

    def __init__(self, channel):
    pass
        """Constructor.

        Args:
    pass
            channel: A grpc.Channel.
        """
        self.AnalyzeImage = channel.unary_unary(
                '/look_service.LookService/AnalyzeImage',
                request_serializer=look__service__pb2.AnalyzeImageRequest.SerializeToString,
                response_deserializer=look__service__pb2.AnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeTongue = channel.unary_unary(
                '/look_service.LookService/AnalyzeTongue',
                request_serializer=look__service__pb2.TongueRequest.SerializeToString,
                response_deserializer=look__service__pb2.TongueAnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeFace = channel.unary_unary(
                '/look_service.LookService/AnalyzeFace',
                request_serializer=look__service__pb2.FaceRequest.SerializeToString,
                response_deserializer=look__service__pb2.FaceAnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeBody = channel.unary_unary(
                '/look_service.LookService/AnalyzeBody',
                request_serializer=look__service__pb2.BodyRequest.SerializeToString,
                response_deserializer=look__service__pb2.BodyAnalysisResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/look_service.LookService/HealthCheck',
                request_serializer=look__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=look__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)

class LookServiceServicer(object):
    pass
    """望诊服务 - 负责舌象、面色、形体等图像分析
    """

    def AnalyzeImage(self, request, context):
    pass
        """分析图像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTongue(self, request, context):
    pass
        """舌象分析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeFace(self, request, context):
    pass
        """面色分析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeBody(self, request, context):
    pass
        """形体分析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
    pass
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_LookServiceServicer_to_server(servicer, server):
    pass
    rpc_method_handlers = {
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=look__service__pb2.AnalyzeImageRequest.FromString,
                    response_serializer=look__service__pb2.AnalysisResponse.SerializeToString),
            'AnalyzeTongue': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTongue,
                    request_deserializer=look__service__pb2.TongueRequest.FromString,
                    response_serializer=look__service__pb2.TongueAnalysisResponse.SerializeToString),
            'AnalyzeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFace,
                    request_deserializer=look__service__pb2.FaceRequest.FromString,
                    response_serializer=look__service__pb2.FaceAnalysisResponse.SerializeToString),
            'AnalyzeBody': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBody,
                    request_deserializer=look__service__pb2.BodyRequest.FromString,
                    response_serializer=look__service__pb2.BodyAnalysisResponse.SerializeToString),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=look__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=look__service__pb2.HealthCheckResponse.SerializeToString)}
    generic_handler = grpc.method_handlers_generic_handler(
            'look_service.LookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler))
    server.add_registered_method_handlers('look_service.LookService', rpc_method_handlers)

class LookService(object):
    pass
    """望诊服务 - 负责舌象、面色、形体等图像分析
    """

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/look_service.LookService/AnalyzeImage',
            look__service__pb2.AnalyzeImageRequest.SerializeToString,
            look__service__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTongue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/look_service.LookService/AnalyzeTongue',
            look__service__pb2.TongueRequest.SerializeToString,
            look__service__pb2.TongueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/look_service.LookService/AnalyzeFace',
            look__service__pb2.FaceRequest.SerializeToString,
            look__service__pb2.FaceAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/look_service.LookService/AnalyzeBody',
            look__service__pb2.BodyRequest.SerializeToString,
            look__service__pb2.BodyAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            self.compression=None,
            wait_for_ready=None,
            timeout=None,:
            self.metadata=None):
    pass
        return grpc.experimental.unary_unary(
            request,
            target,
            '/look_service.LookService/HealthCheck',
            look__service__pb2.HealthCheckRequest.SerializeToString,
            look__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            self.compression,
            wait_for_ready,
            timeout,
            self.metadata,
            _registered_method=True)
