// 索克生活 - 主屏幕模块统一导出/;/g/;
// 主屏幕相关组件的入口文件/;,/g/;
export { default as HomeScreen } from "./HomeScreen";""/;"/g"/;
(');'';'';
';'';
// 导出类型定义'/;,'/g'/;
export type { Contact, ContactGroup } from "./HomeScreen";""/;"/g"/;
(');'';'';
';'';
// 导出联系人类型枚举'/;,'/g'/;
export type ContactType = 'agent' | 'doctor' | 'user' | 'supplier' | 'service';';'';
(');'';
export type ContactStatus = 'online' | 'offline' | 'busy' | 'away';';'';
(');'';'';
''';