apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: corn-maze-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.suoke.life/suoke/manifests.git'
    path: apps/corn-maze-service
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: suoke
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 