apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corn-maze-uploads-pvc
  namespace: suoke
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-disk-ssd
  resources:
    requests:
      storage: 10Gi 