apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
  namespace: suoke
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: rag-service
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: ENABLE_CACHING
          value: "true"
        - name: CACHE_TTL
          value: "3600"
        - name: TELEMETRY_ENABLED
          value: "true"
        - name: TRACING_SAMPLE_RATE
          value: "0.1"
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
      nodeSelector:
        node-role: app
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rag-service
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      terminationGracePeriodSeconds: 90 