# 索克生活APP认证服务默认配置

# 服务配置
service:
  name: auth-service
  version: 1.0.0
  port: 8080
  debug: false
  env: development # development, testing, production

# 数据库配置
database:
  type: postgresql
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  database: ${DB_NAME:auth_db}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:postgres}
  pool_size: 20
  max_overflow: 10
  ssl: false

# Redis配置
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:0}
  password: ${REDIS_PASSWORD:}
  ssl: false
  max_connections: 10

# JWT配置
jwt:
  secret: ${JWT_SECRET:super_secret_key_change_in_production}
  algorithm: HS256
  access_token_expire_minutes: ${ACCESS_TOKEN_EXPIRE_MINUTES:30}
  refresh_token_expire_days: ${REFRESH_TOKEN_EXPIRE_DAYS:7}

# CORS配置
cors:
  allow_origins:
    - https://app.suoke.life
    - https://api.suoke.life
    - http://localhost:3000
  allow_credentials: true
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Accept
    - Authorization
    - Content-Type
    - X-Request-ID

# 日志配置
logging:
  level: ${LOG_LEVEL:INFO}
  format: json
  output: stdout
  log_dir: ${LOG_DIR:/var/log/suoke/auth-service}

# 追踪配置
tracing:
  enabled: true
  exporter: otlp
  otlp:
    endpoint: ${OTLP_ENDPOINT:localhost:4317}
    insecure: true

# 消息队列配置
pulsar:
  service_url: ${PULSAR_URL:pulsar://localhost:6650}
  admin_url: ${PULSAR_ADMIN_URL:http://localhost:8080}
  tenant: suoke
  namespace: auth
  producer_topics:
    user_created: persistent://suoke/auth/user-created
    user_updated: persistent://suoke/auth/user-updated
    user_deleted: persistent://suoke/auth/user-deleted
    user_login: persistent://suoke/auth/user-login
  consumer_topics:
    user_verification: persistent://suoke/auth/user-verification
    role_changes: persistent://suoke/auth/role-changes

# 安全配置
security:
  password_policies:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: false
  rate_limiting:
    enabled: true
    login_limit: 5 # 每IP每分钟最大尝试次数
    register_limit: 3 # 每IP每分钟最大注册次数
  mfa:
    enabled: true
    default_type: TOTP
    issuer: "索克生活"

# gRPC配置
grpc:
  port: 9090
  max_workers: 10
  reflection: true
  interceptors:
    - auth
    - logging
    - tracing

# 区块链配置
blockchain:
  enabled: false # 在生产环境中启用
  provider: ethereum
  network: rinkeby
  contract_address: "0x0000000000000000000000000000000000000000"
  private_key: ${BLOCKCHAIN_PRIVATE_KEY:}

# 缓存配置
cache:
  type: redis
  ttl: 300 # 秒
  prefix: auth:

# 健康检查配置
health:
  port: 8081
  check_interval: 10 # 秒 