apiVersion: v1
data:
  BLOCKCHAIN_CHAIN_ID: "2035"
  BLOCKCHAIN_NODE_URL: https://gwan-ssl.wandevs.org:46891
  DB_CONN_MAX_LIFETIME: "3600"
  DB_HOST: postgres-service
  DB_MAX_IDLE_CONNS: "10"
  DB_MAX_OPEN_CONNS: "30"
  DB_NAME: suoke
  DB_PORT: "5432"
  DB_SSL_MODE: disable
  EMBEDDING_BATCH_SIZE: "5"
  EMBEDDING_DIMENSIONS: "1536"
  EMBEDDING_MODEL: text-embedding-ada-002
  ENVIRONMENT: production
  LOG_FORMAT: json
  LOG_LEVEL: info
  LOG_OUTPUT: both
  METRICS_ENABLED: "true"
  SERVER_PORT: "8083"
  TEXT_SPLITTER_CHUNK_OVERLAP: "200"
  TEXT_SPLITTER_CHUNK_SIZE: "1000"
  TRACE_ENABLED: "true"
  VECTOR_STORE_HOST: milvus-service
  VECTOR_STORE_PORT: "19530"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"BLOCKCHAIN_CHAIN_ID":"2035","BLOCKCHAIN_NODE_URL":"https://gwan-ssl.wandevs.org:46891","DB_CONN_MAX_LIFETIME":"3600","DB_HOST":"postgres-service","DB_MAX_IDLE_CONNS":"10","DB_MAX_OPEN_CONNS":"30","DB_NAME":"suoke","DB_PORT":"5432","DB_SSL_MODE":"disable","EMBEDDING_BATCH_SIZE":"5","EMBEDDING_DIMENSIONS":"1536","EMBEDDING_MODEL":"text-embedding-ada-002","ENVIRONMENT":"production","LOG_FORMAT":"json","LOG_LEVEL":"info","LOG_OUTPUT":"both","METRICS_ENABLED":"true","SERVER_PORT":"8083","TEXT_SPLITTER_CHUNK_OVERLAP":"200","TEXT_SPLITTER_CHUNK_SIZE":"1000","TRACE_ENABLED":"true","VECTOR_STORE_HOST":"milvus-service","VECTOR_STORE_PORT":"19530"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"knowledge-base-service","part-of":"suoke-life"},"name":"knowledge-base-config","namespace":"suoke-prod"}}
  creationTimestamp: "2025-04-05T17:18:49Z"
  labels:
    app: knowledge-base-service
    part-of: suoke-life
  name: knowledge-base-config
  namespace: suoke-prod
  resourceVersion: "10099648"
  uid: 48804077-69bc-4ff0-9df2-588fe7271a46
