# 老克智能体服务配置文件

# 服务基本配置
service:
  name: "laoke-service"
  version: "1.0.0"
  debug: false
  environment: "production"

# 服务器配置
server:
  grpc:
    host: "0.0.0.0"
    port: 50051
    max_workers: 10
    max_message_length: 4194304  # 4MB
  
  rest:
    host: "0.0.0.0"
    port: 8080
    workers: 4
    
  cors:
    allowed_origins: ["*"]
    allow_credentials: true
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

# 数据库配置
database:
  type: "sqlite"
  sqlite:
    path: "data/laoke.db"
    pool_size: 10
    timeout: 30
  
  # PostgreSQL配置（可选）
  postgres:
    host: "localhost"
    port: 5432
    user: "laoke"
    password: "${DB_PASSWORD}"
    database: "laoke_service"
    pool_size: 10
    ssl_mode: "disable"

# 缓存配置
cache:
  backend: "memory"  # memory, redis
  redis:
    url: "redis://localhost:6379"
    db: 0
    password: "${REDIS_PASSWORD}"
  
  default_ttl: 3600  # 1小时
  max_memory_items: 10000
  key_prefix: "laoke:"

# 智能体配置
agent:
  # 模型配置
  models:
    llm:
      primary_model: "gpt-4o-mini"
      fallback_model: "llama-3-8b"
      api_key: "${OPENAI_API_KEY}"
      base_url: "https://api.openai.com/v1"
      timeout: 30
      max_retries: 3
  
  # 对话配置
  conversation:
    system_prompt: |
      你是老克，一位资深的中医专家和教育者，专注于中医知识传播、社群管理和教育内容创建。
      
      你的核心职责：
      1. 传播准确的中医知识，包括理论、诊断、治疗方法等
      2. 管理中医学习社群，促进成员间的交流和学习
      3. 创建高质量的中医教育内容，适合不同水平的学习者
      4. 提供个性化的中医学习路径和建议
      
      你的特点：
      - 知识渊博，对中医经典和现代应用都有深入理解
      - 善于教学，能够将复杂的概念简化为易懂的内容
      - 耐心细致，关注每个学习者的需求和进步
      - 严谨负责，确保传播的知识准确可靠
      
      请始终保持专业、友善和耐心的态度，用通俗易懂的语言回答问题。
    
    max_history_turns: 20
    max_tokens_per_message: 4096
  
  # 会话管理
  session_timeout: 3600  # 1小时
  max_concurrent_sessions: 1000
  cleanup_interval: 300  # 5分钟

# 速率限制配置
rate_limit:
  global_rules:
    - requests: 100
      window: 60  # 每分钟100请求
      algorithm: "sliding_window"
    - requests: 1000
      window: 3600  # 每小时1000请求
      algorithm: "sliding_window"
  
  user_rules:
    "premium_user":
      requests: 200
      window: 60
      algorithm: "token_bucket"
      burst: 50

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    enabled: true
    path: "logs/laoke-service.log"
    max_size: "100MB"
    backup_count: 5
  
  console:
    enabled: true
    colored: true

# 指标配置
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  
  # 自定义指标
  custom_metrics:
    - name: "agent_requests_total"
      type: "counter"
      description: "Total number of agent requests"
      labels: ["request_type", "user_id"]
    
    - name: "agent_response_time"
      type: "histogram"
      description: "Agent response time in seconds"
      buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]

# 健康检查配置
health:
  enabled: true
  path: "/health"
  checks:
    - name: "database"
      timeout: 5
    - name: "cache"
      timeout: 3
    - name: "llm_api"
      timeout: 10

# 安全配置
security:
  # API密钥验证
  api_key:
    enabled: false
    header_name: "X-API-Key"
    keys: []
  
  # JWT配置
  jwt:
    enabled: false
    secret: "${JWT_SECRET}"
    algorithm: "HS256"
    expiration: 3600
  
  # 输入验证
  validation:
    max_request_size: 1048576  # 1MB
    sanitize_html: true
    check_sql_injection: true

# 外部服务配置
external_services:
  # 知识库服务
  knowledge_service:
    enabled: true
    url: "http://localhost:8081"
    timeout: 10
    api_key: "${KNOWLEDGE_SERVICE_API_KEY}"
  
  # 用户服务
  user_service:
    enabled: true
    url: "http://localhost:8082"
    timeout: 5
    api_key: "${USER_SERVICE_API_KEY}"

# 特性开关
features:
  enable_caching: true
  enable_rate_limiting: true
  enable_metrics: true
  enable_tracing: false
  enable_content_moderation: true
  enable_learning_analytics: true

# 开发配置
development:
  debug: true
  hot_reload: true
  mock_external_services: false
  log_sql_queries: false 