# 老克智能体服务默认配置
service:
  name: laoke-service
  version: 1.0.0
  description: 索克生活APP的社区健康知识智能体，提供社区健康教育和知识管理

server:
  host: 0.0.0.0
  port: 8082
  debug: false
  workers: 4
  timeout: 60
  cors:
    enabled: true
    origins:
      - "*"

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/laoke-service.log
  max_size: 10485760  # 10MB
  backup_count: 5

metrics:
  enabled: true
  report_interval: 60  # 秒

conversation:
  system_prompt: "你是老克，索克生活APP的知识传播平台智能体，你专注于中医知识传播、社群管理和教育培训。"
  max_history_turns: 20

models:
  llm:
    primary_model: gpt-4o-mini
    fallback_model: llama-3-8b
    api_key: ${OPENAI_API_KEY}
    api_base: ${OPENAI_API_BASE:-https://api.openai.com/v1}
    org_id: ${OPENAI_ORG_ID}
    timeout: 60
  
  local_llm:
    endpoint_url: http://localhost:8000/v1
    available_models:
      - llama-3-8b
      - llama-3-70b
    default_model: llama-3-8b
    max_tokens: 4096
  
  zhipu:
    api_key: ${ZHIPU_API_KEY}
    available_models:
      - glm-4
      - glm-3-turbo
  
  baidu:
    api_key: ${BAIDU_API_KEY}
    secret_key: ${BAIDU_SECRET_KEY}
    api_url: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/
    available_models:
      - ernie-bot-4
      - ernie-bot

# 标准数据库配置
database:
  # 主数据库配置
  primary:
    type: postgresql
    host: ${DB_HOST:-localhost}
    port: ${DB_PORT:-5432}
    username: ${DB_USER:-postgres}
    password: ${DB_PASS:-postgres}
    database: ${DB_NAME:-laoke_service}
    
    # 连接池配置
    pool:
      min_size: 5
      max_size: ${DB_POOL_SIZE:-20}
      max_overflow: ${DB_MAX_OVERFLOW:-10}
      timeout: ${DB_POOL_TIMEOUT:-30}
      recycle: ${DB_POOL_RECYCLE:-3600}
      use_lifo: true
      echo: ${DB_ECHO:-false}
    
    # 性能优化参数
    optimization:
      prepared_statement_cache_size: 100
      statement_timeout: 30000
      idle_in_transaction_session_timeout: 60000
      effective_cache_size: "4GB"
      maintenance_work_mem: "64MB"
      max_parallel_workers_per_gather: 2
      enable_partitionwise_join: true
    
    # 连接参数
    options:
      application_name: "laoke_service"
      client_encoding: "UTF8"
      connect_timeout: 10
      keepalives: 1
      keepalives_idle: 60
    
    # 事务隔离级别
    isolation_level: "READ COMMITTED"
  
  # 只读副本配置（用于读写分离）
  replicas:
    enabled: ${DB_REPLICAS_ENABLED:-false}
    strategy: "round_robin"
    nodes:
      - host: ${DB_REPLICA1_HOST}
        port: ${DB_REPLICA1_PORT:-5432}
        username: ${DB_REPLICA1_USER:-postgres}
        password: ${DB_REPLICA1_PASS:-postgres}
        database: ${DB_REPLICA1_NAME:-laoke_service}
        pool:
          min_size: 2
          max_size: ${DB_REPLICA1_POOL_SIZE:-10}
          max_overflow: 5
          timeout: 20
  
  # SQLite配置（用于本地存储）
  sqlite:
    path: ${SQLITE_PATH:-data/local.db}
    journal_mode: "WAL"
    synchronous: "NORMAL"
    busy_timeout: 5000
    cache_size: 2000
    temp_store: "MEMORY"
  
  # MongoDB配置（用于知识内容存储）
  mongodb:
    uri: ${MONGODB_URI:-mongodb://localhost:27017}
    database: ${MONGODB_DB:-laoke_knowledge}
    min_pool_size: 5
    max_pool_size: 20
    max_connection_idle_time: 60000
    connect_timeout: 20000
    socket_timeout: 300000
  
  # 向量数据库配置
  vector:
    type: milvus
    host: ${VECTOR_DB_HOST:-localhost}
    port: ${VECTOR_DB_PORT:-19530}
    collection: ${VECTOR_DB_COLLECTION:-laoke_vectors}
    dimension: 768
    metric_type: "IP"
    partition_key: "source"
    replica_number: 1
  
  # 缓存配置
  cache:
    type: redis
    host: ${REDIS_HOST:-localhost}
    port: ${REDIS_PORT:-6379}
    db: ${REDIS_DB:-0}
    password: ${REDIS_PASS}
    ttl: ${REDIS_TTL:-3600}
    key_prefix: "laoke:"
    
    # Redis连接池配置
    pool:
      min_idle: 5
      max_idle: 20
      max_active: 50
      max_wait: 3000
      timeout: 2000
    
    # 本地缓存配置（双层缓存）
    local:
      enabled: true
      max_size: 10000
      ttl: 300
  
  # 监控配置
  monitoring:
    query_timeout_threshold: 1000
    slow_query_log: true
    slow_query_threshold: 500
    connection_stats: true
    query_stats: true

queues:
  message_bus:
    host: ${KAFKA_HOST:-localhost}
    port: ${KAFKA_PORT:-9092}
    topic_prefix: laoke
    consumer_group: laoke-service
    topics:
      - knowledge-sharing
      - community-events
      - edu-content

integrations:
  med_knowledge:
    url: ${MED_KNOWLEDGE_URL:-http://localhost:8081}
    api_key: ${MED_KNOWLEDGE_KEY}
  
  education_platform:
    url: ${EDU_PLATFORM_URL}
    api_key: ${EDU_PLATFORM_KEY}
    timeout: 30
  
  community_system:
    url: ${COMMUNITY_SYSTEM_URL}
    api_key: ${COMMUNITY_SYSTEM_KEY}
    timeout: 30

knowledge_repository:
  vector_db:
    type: milvus
    host: ${MILVUS_HOST:-localhost}
    port: ${MILVUS_PORT:-19530}
    collection: tcm_knowledge
  
  document_store:
    type: elasticsearch
    host: ${ES_HOST:-localhost}
    port: ${ES_PORT:-9200}
    index: tcm_documents

security:
  jwt:
    secret: ${JWT_SECRET}
    algorithm: HS256
    expires: 3600  # 1小时
  
  api_keys:
    enabled: true
    header_name: X-API-Key

resilience:
  circuit_breaker:
    failure_threshold: 5
    recovery_time: 30
  
  rate_limiter:
    max_calls: 60
    time_period: 60

telemetry:
  tracing:
    enabled: ${TRACING_ENABLED:-false}
    exporter: otlp
    endpoint: ${OTLP_ENDPOINT:-localhost:4317}
    service_name: laoke-service
    environment: ${SERVICE_ENV:-development}
    sampler: always_on   # always_on, always_off, trace_id_ratio
    sampler_ratio: 1.0   # 采样率，仅在trace_id_ratio采样器中使用
  metrics:
    enabled: ${METRICS_ENABLED:-true}
    exporter: prometheus
    endpoint: ${METRICS_ENDPOINT:-localhost:9090}
    export_interval: 15  # 秒

community:
  knowledge_base:
    enabled: true
    sync_interval: 3600  # 每小时同步一次
    categories:
      - health_education
      - preventive_medicine
      - tcm_practices
      - diet_nutrition
      - exercise_guidance