apiVersion: apps/v1
kind: Deployment
metadata:
  name: laoke-service
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      containers:
      - name: laoke-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: production
        - name: CLUSTER_ENABLED
          value: "true" 