apiVersion: apps/v1
kind: Deployment
metadata:
  name: laoke-service
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: laoke-service
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false