version: '3.8'

services:
  med-knowledge:
    build: 
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: med-knowledge
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=suoke_password
    depends_on:
      - neo4j
    networks:
      - suoke-network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/suoke_password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - suoke-network

networks:
  suoke-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs: