# 索克生活触诊服务配置文件

# 服务配置
service:
  name: "palpation-service"
  version: "1.0.0"
  description: "索克生活触诊服务 - 基于AI的中医触诊智能分析微服务"
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  workers: 1

# 数据库配置
database:
  url: "${DATABASE_URL:postgresql://localhost:5432/palpation}"
  echo: false
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Redis 配置
redis:
  url: "${REDIS_URL:redis://localhost:6379/0}"
  max_connections: 10
  retry_on_timeout: true
  socket_timeout: 5
  socket_connect_timeout: 5

# 日志配置
logging:
  level: "INFO"
  format: "json"
  handlers:
    - type: "console"
      level: "INFO"
    - type: "file"
      level: "DEBUG"
      filename: "logs/palpation.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
  prometheus:
    enabled: true
    path: "/metrics"

# 安全配置
security:
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
  rate_limiting:
    enabled: true
    requests_per_minute: 100

# 触诊分析配置
palpation:
  # 传感器配置
  sensors:
    pressure:
      enabled: true
      sampling_rate: 1000  # Hz
      sensitivity: 0.1
    temperature:
      enabled: true
      sampling_rate: 10  # Hz
      accuracy: 0.1  # °C
    texture:
      enabled: true
      resolution: "high"
  
  # AI 模型配置
  models:
    pulse_analysis:
      model_path: "models/pulse_classifier.pkl"
      confidence_threshold: 0.8
    texture_analysis:
      model_path: "models/texture_classifier.pkl"
      confidence_threshold: 0.75
    temperature_analysis:
      model_path: "models/temperature_analyzer.pkl"
      confidence_threshold: 0.85
  
  # 分析参数
  analysis:
    window_size: 5  # 秒
    overlap: 0.5
    min_duration: 10  # 秒
    max_duration: 300  # 秒

# 缓存配置
cache:
  default_ttl: 3600  # 1小时
  max_size: 1000
  analysis_results_ttl: 86400  # 24小时
  sensor_data_ttl: 300  # 5分钟

# 外部服务配置
external_services:
  xiaoai_service:
    url: "${XIAOAI_SERVICE_URL:http://localhost:8001}"
    timeout: 30
    retry_attempts: 3
  
  xiaoke_service:
    url: "${XIAOKE_SERVICE_URL:http://localhost:8002}"
    timeout: 30
    retry_attempts: 3
  
  health_data_service:
    url: "${HEALTH_DATA_SERVICE_URL:http://localhost:8003}"
    timeout: 30
    retry_attempts: 3

# 消息队列配置
message_queue:
  broker_url: "${CELERY_BROKER_URL:redis://localhost:6379/1}"
  result_backend: "${CELERY_RESULT_BACKEND:redis://localhost:6379/2}"
  task_serializer: "json"
  result_serializer: "json"
  accept_content: ["json"]
  timezone: "Asia/Shanghai"

# 开发配置
development:
  auto_reload: true
  debug_toolbar: true
  profiling: false
  mock_sensors: true

# 生产配置
production:
  auto_reload: false
  debug_toolbar: false
  profiling: true
  mock_sensors: false 