global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'palpation-service-monitor'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # 触诊服务监控
  - job_name: 'palpation-service'
    static_configs:
      - targets: ['palpation-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 存储配置
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB 