apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secrets.yaml
- horizontal-pod-autoscaler.yaml

commonLabels:
  app: rag-service
  service: rag-service 