apiVersion: v1
kind: Secret
metadata:
  name: rag-service-secrets
  namespace: suoke
  labels:
    app: rag-service
type: Opaque
data:
  # 这些是示例值，实际部署时应使用真实的加密密钥
  openai-api-key: ${OPENAI_API_KEY_BASE64} 