apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: suoke
  labels:
    app: rag-service
    service: rag-service
spec:
  selector:
    app: rag-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 9000
    targetPort: 9000
  type: ClusterIP 