# LLM API密钥配置
# 注意：这是模板文件，实际部署时需要替换为真实的API密钥
apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  namespace: suoke-life
type: Opaque
data:
  # 注意：以下是base64编码的示例值，实际使用时需要替换
  # 使用命令生成：echo -n "your-api-key" | base64
  openai-key: "eW91ci1vcGVuYWktYXBpLWtleQ=="  # your-openai-api-key
  anthropic-key: "eW91ci1hbnRocm9waWMtYXBpLWtleQ=="  # your-anthropic-api-key
  google-key: "eW91ci1nb29nbGUtYXBpLWtleQ=="  # your-google-api-key
---
# Redis缓存服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  namespace: suoke-life
  labels:
    app: redis
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: suoke-life
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP 