version: '3.8'

services:
  suoke-bench-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: suoke-bench-service
    ports:
      - "8000:8000"  # REST API
      - "50051:50051"  # gRPC
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - GRPC_PORT=50051
      - PORT=8000
      - DEBUG=false
    volumes:
      - ../data:/app/data
      - ../reports:/app/reports
    networks:
      - suoke-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  suoke-network:
    name: suoke-network
    external: true