apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
      queryTimeout: 120s
      httpMethod: POST
    editable: true
    isDefault: true 