apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: suoke-services
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: suoke
  namespaceSelector:
    matchNames:
    - suoke
    - suoke-dev
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics