// 主屏幕/;,/g/;
export { default as ChatDetailScreen } from "./main/ChatDetailScreen";""/;"/g"/;
(');'';
export { default as HomeScreen } from "./main/HomeScreen";""/;"/g"/;
(');'';'';
';'';
// 认证屏幕'/;,'/g'/;
export { default as ForgotPasswordScreen } from "./auth/ForgotPasswordScreen";""/;"/g"/;
(');'';
export { default as LoginScreen } from "./auth/LoginScreen";""/;"/g"/;
(');'';
export { default as RegisterScreen } from "./auth/RegisterScreen";""/;"/g"/;
(');'';'';
';'';
// 四个智能体屏幕'/;,'/g'/;
export { default as ExploreScreen } from "./explore/ExploreScreen";""/;"/g"/;
(');'';
export { default as LifeScreen } from "./life/LifeScreen";""/;"/g"/;
(');'';
export { default as SuokeScreen } from "./suoke/SuokeScreen";""/;"/g"/;
(');'';'';
';'';
// 诊断屏幕'/;,'/g'/;
export { default as DiagnosisDetailScreen } from "./diagnosis/DiagnosisDetailScreen";""/;"/g"/;
(');'';
export { default as FiveDiagnosisScreen } from "./diagnosis/FiveDiagnosisScreen";""/;"/g"/;
(');'';'';
';'';
// 个人资料屏幕'/;,'/g'/;
export { default as HealthRecordsScreen } from "./profile/HealthRecordsScreen";""/;"/g"/;
(');'';
export { default as ProfileScreen } from "./profile/ProfileScreen";""/;"/g"/;
(');'';
export { default as SettingsScreen } from "./profile/SettingsScreen";""/;"/g"/;
(');'';'';
';'';
// 生活健康屏幕'/;,'/g'/;
export { default as ExerciseScreen } from "./life/ExerciseScreen";""/;"/g"/;
(');'';
export { default as HealthDashboard } from "./life/HealthDashboard";""/;"/g"/;
(');'';
export { default as NutritionScreen } from "./life/NutritionScreen";""/;"/g"/;
(');'';'';
';'';
// 演示屏幕'/;,'/g'/;
export { default as ComponentDemoScreen } from "./demo/ComponentDemoScreen";""/;"/g"/;
(');'';
export { default as DemoScreen } from "./demo/DemoScreen";""/;"/g"/;
(');'';'';
';'';
// 组件屏幕'/;,'/g'/;
export { default as AgentChatScreen } from "./agents/AgentChatScreen";""/;"/g"/;
(');'';
export { default as HealthAnalysisScreen } from "./components/HealthAnalysisScreen";""/;"/g"/;
(');'';'';
''';