global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'suoke-life-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # API网关监控
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # 认证服务监控
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: /metrics
    scrape_interval: 15s

  # 用户服务监控
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8082']
    metrics_path: /metrics
    scrape_interval: 15s

  # 小艾智能体服务监控
  - job_name: 'xiaoai-service'
    static_configs:
      - targets: ['xiaoai-service:50051']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # 小克智能体服务监控
  - job_name: 'xiaoke-service'
    static_configs:
      - targets: ['xiaoke-service:50052']
    metrics_path: /metrics
    scrape_interval: 10s

  # 老克智能体服务监控
  - job_name: 'laoke-service'
    static_configs:
      - targets: ['laoke-service:50053']
    metrics_path: /metrics
    scrape_interval: 10s

  # 索儿智能体服务监控
  - job_name: 'soer-service'
    static_configs:
      - targets: ['soer-service:50054']
    metrics_path: /metrics
    scrape_interval: 10s

  # 健康数据服务监控
  - job_name: 'health-data-service'
    static_configs:
      - targets: ['health-data-service:8083']
    metrics_path: /metrics
    scrape_interval: 15s

  # 区块链服务监控
  - job_name: 'blockchain-service'
    static_configs:
      - targets: ['blockchain-service:8084']
    metrics_path: /metrics
    scrape_interval: 30s

  # RAG服务监控
  - job_name: 'rag-service'
    static_configs:
      - targets: ['rag-service:8085']
    metrics_path: /metrics
    scrape_interval: 15s

  # 消息总线监控
  - job_name: 'message-bus'
    static_configs:
      - targets: ['message-bus:8086']
    metrics_path: /metrics
    scrape_interval: 15s

  # PostgreSQL数据库监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # MongoDB监控
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # RabbitMQ监控
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node Exporter (系统监控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor (容器监控)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Kubernetes API Server监控
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes节点监控
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pod监控
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # 自定义业务指标监控
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /api/v1/metrics/business
    scrape_interval: 30s
    params:
      module: [business]

  # 健康检查监控
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'api-gateway:8080'
        - 'auth-service:8081'
        - 'user-service:8082'
        - 'health-data-service:8083'
        - 'blockchain-service:8084'
        - 'rag-service:8085'
        - 'message-bus:8086'
    metrics_path: /health
    scrape_interval: 10s
    scrape_timeout: 5s

# 远程写入配置（可选，用于长期存储）
remote_write:
  - url: "http://thanos-receive:19291/api/v1/receive"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# 远程读取配置（可选）
remote_read:
  - url: "http://thanos-query:9090/api/v1/query"
    read_recent: true
