server:
  host: "0.0.0.0"
  port: 50052
  max_workers: 10
  max_concurrent_rpcs: 100
  timeout: 60
  api_version: "v1"
  enable_reflection: true
  enable_health_check: true

models:
  # 语音分析模型
  voice_model:
    name: "voice_feature_analyzer"
    path: "/app/models/voice_feature_analyzer"
    version: "1.0.0"
    batch_size: 16
    device: "cuda:0"  # 使用GPU，如果是CPU环境则设为"cpu"
    precision: "fp16"
    threshold: 0.65
    max_sequence_length: 10000
    sampling_rate: 16000
    preload: true
    cache_size: 10

  # 声音分析模型（咳嗽、呼吸等）
  sound_model:
    name: "sound_feature_analyzer"
    path: "/app/models/sound_feature_analyzer"
    version: "1.0.0"
    batch_size: 8
    device: "cuda:0"
    precision: "fp16"
    threshold: 0.7
    preload: true
    cache_size: 5

  # 情绪分析模型
  emotion_model:
    name: "emotion_detector"
    path: "/app/models/emotion_detector"
    version: "1.0.0"
    batch_size: 16
    device: "cuda:0"
    precision: "fp16"
    threshold: 0.6
    preload: true
    cache_size: 5

  # 方言识别模型
  dialect_model:
    name: "dialect_identifier"
    path: "/app/models/dialect_identifier"
    version: "1.0.0"
    batch_size: 8
    device: "cuda:0"
    precision: "fp16"
    threshold: 0.6
    preload: false
    cache_size: 5

  # 语音转写模型
  transcription_model:
    name: "whisper_medium"
    path: "/app/models/whisper_medium"
    version: "1.0.0"
    batch_size: 1
    device: "cuda:0"
    precision: "fp16"
    language: "zh"
    temperature: 0.0
    beam_size: 5
    preload: true
    cache_size: 2

# 音频处理配置
audio_processing:
  default_sample_rate: 16000
  default_channels: 1
  supported_formats: ["wav", "mp3", "flac", "ogg", "m4a"]
  max_duration: 300  # 最大音频长度（秒）
  min_duration: 1    # 最小音频长度（秒）
  max_file_size: 50  # MB
  chunk_size: 4096   # 处理音频的分块大小
  noise_reduction: true
  normalize_volume: true
  vad_enabled: true  # 语音活动检测
  vad_threshold: 0.5
  preprocess_cache_size: 100
  temp_dir: "/tmp/listen_service"

# 数据库配置
database:
  type: "mongodb"
  host: "mongodb"
  port: 27017
  username: "${MONGO_USERNAME}"
  password: "${MONGO_PASSWORD}"
  database: "listen_service"
  auth_source: "admin"
  connection_pool_size: 10
  timeout: 5
  retry_writes: true
  retry_reads: true
  collection_prefix: "listen_"

# 缓存配置
cache:
  type: "redis"
  host: "redis"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  ttl: 3600  # 默认过期时间（秒）
  max_connections: 10
  features_ttl: 86400  # 特征缓存24小时

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: true
  log_file: "/var/log/listen_service/service.log"
  log_to_console: true
  max_log_file_size: 50  # MB
  max_log_files: 5
  request_log: true

# 监控和指标配置
monitoring:
  prometheus:
    enabled: true
    host: "0.0.0.0"
    port: 9090
    path: "/metrics"
    collect_default_metrics: true
    push_gateway: false
    push_interval: 10
  tracing:
    enabled: true
    exporter: "jaeger"
    jaeger_agent_host: "jaeger"
    jaeger_agent_port: 6831
    service_name: "listen-service"
    sample_rate: 0.1
  health_check:
    enabled: true
    interval: 60
    timeout: 10
    endpoints:
      database: true
      cache: true
      models: true

# 访问控制
security:
  # 授权令牌验证
  auth:
    enabled: true
    jwt_secret: "${JWT_SECRET}"
    token_expire: 86400  # 24小时
    token_issuer: "suoke-life"
    bypass_internal: true
  # 调用访问控制
  acl:
    enabled: true
    allowed_services:
      - "xiaoai-service"
      - "inquiry-service"
      - "admin-service"
    require_auth: true

# 与其他服务的集成
integrations:
  # 与小艾服务的集成
  xiaoai_service:
    host: "xiaoai-service"
    port: 50051
    timeout: 10
    retry_count: 3
    retry_interval: 1
    use_tls: false
    max_connections: 10
  
  # 与问诊服务的集成
  inquiry_service:
    host: "inquiry-service"
    port: 50053
    timeout: 10
    retry_count: 3
    retry_interval: 1
    use_tls: false
    max_connections: 5

# 中医服务特定配置
tcm:
  # 中医证型参数
  syndrome_patterns:
    enabled: true
    model_path: "/app/models/tcm_syndrome_classifier"
    threshold: 0.65
    top_k: 3
    feature_importance_threshold: 0.3
  
  # 体质关联参数
  constitution_mapping:
    enabled: true
    model_path: "/app/models/constitution_voice_mapping"
    threshold: 0.6
    feature_mapping_file: "/app/config/feature_constitution_map.json"

# 开发环境配置
dev:
  debug: false
  mock_models: false
  profile_enabled: true
  test_audio_path: "/app/test_data" 