# 闻诊服务优化配置文件
# 版本: 2.0
# 更新日期: 2024-01-20

# 服务器配置
server:
  host: "0.0.0.0"
  port: 50052
  max_workers: 16  # 增加工作线程数
  max_concurrent_rpcs: 200  # 增加并发RPC数量
  enable_reflection: true
  
  # gRPC优化选项
  grpc_options:
    max_send_message_length: 100485760  # 100MB
    max_receive_message_length: 100485760  # 100MB
    keepalive_time_ms: 30000
    keepalive_timeout_ms: 5000
    keepalive_permit_without_calls: true
    http2_max_pings_without_data: 0
    http2_min_time_between_pings_ms: 10000

# 音频处理配置
audio_processing:
  # 基本参数
  default_sample_rate: 16000
  default_channels: 1
  supported_formats: ["wav", "mp3", "flac", "m4a", "aac", "ogg"]
  max_duration: 600  # 增加到10分钟
  min_duration: 0.3  # 减少到0.3秒
  max_file_size: 100  # MB，增加到100MB
  chunk_size: 8192  # 增加块大小
  
  # 性能优化
  enable_gpu: true
  batch_processing: true
  cache_enabled: true
  max_concurrent_tasks: 8  # 增加并发任务数
  
  # 预处理选项
  noise_reduction: true
  normalize_volume: true
  vad_enabled: true
  vad_threshold: 0.3  # 降低VAD阈值，更敏感
  
  # 临时目录
  temp_dir: "/tmp/listen_service"

# 中医特色配置
tcm_features:
  # 启用中医特征提取
  enabled: true
  
  # 五脏六腑声音特征映射
  organ_sound_mapping:
    heart: ["高亢", "急促", "断续"]  # 心
    liver: ["弦急", "高亢", "怒声"]  # 肝
    spleen: ["低沉", "缓慢", "思虑"]  # 脾
    lung: ["清亮", "悲伤", "短促"]   # 肺
    kidney: ["低沉", "恐惧", "微弱"] # 肾
  
  # 五志情绪声音特征
  emotion_features:
    joy: ["笑声", "高音", "快节奏"]     # 喜
    anger: ["怒吼", "粗糙", "急促"]     # 怒
    worry: ["叹息", "低沉", "缓慢"]     # 忧
    thought: ["沉思", "平稳", "规律"]   # 思
    fear: ["颤抖", "微弱", "不稳"]      # 恐
  
  # 体质辨识声音特征
  constitution_features:
    qi_deficiency: ["气短", "声低", "懒言"]      # 气虚质
    yang_deficiency: ["声音低微", "语速缓慢"]     # 阳虚质
    yin_deficiency: ["声音嘶哑", "口干"]         # 阴虚质
    phlegm_dampness: ["声音浑浊", "痰音"]        # 痰湿质
    damp_heat: ["声音急躁", "口苦"]              # 湿热质
    blood_stasis: ["声音暗哑", "唇紫"]           # 血瘀质
    qi_stagnation: ["叹息", "情绪波动"]          # 气郁质
    special_constitution: ["过敏", "声音变化"]    # 特禀质
    balanced: ["声音洪亮", "语调平和"]           # 平和质

# 机器学习模型配置
models:
  # 模型路径
  base_path: "./models"
  
  # 语音特征分析模型
  voice_feature_analyzer:
    path: "voice_feature_analyzer"
    version: "v2.0"
    batch_size: 32
    use_gpu: true
    
  # 声音分析模型
  sound_analyzer:
    path: "sound_feature_analyzer"
    version: "v2.0"
    batch_size: 16
    use_gpu: true
    
  # 情绪分析模型
  emotion_detector:
    path: "emotion_detector"
    version: "v2.0"
    batch_size: 32
    use_gpu: true
    
  # 方言检测模型
  dialect_detector:
    path: "dialect_detector"
    version: "v1.5"
    batch_size: 16
    use_gpu: false
    
  # 中医体质分析模型
  tcm_constitution_analyzer:
    path: "tcm_constitution_analyzer"
    version: "v1.0"
    batch_size: 8
    use_gpu: true

# 数据库配置
database:
  mongodb:
    host: "localhost"
    port: 27017
    database: "listen_service"
    username: ""
    password: ""
    
    # 连接池配置
    max_pool_size: 50
    min_pool_size: 5
    max_idle_time_ms: 30000
    
    # 集合配置
    collections:
      audio_records: "audio_records"
      analysis_results: "analysis_results"
      tcm_diagnoses: "tcm_diagnoses"
      user_profiles: "user_profiles"

# 缓存配置
cache:
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: ""
    
    # 连接池配置
    max_connections: 50
    
    # 缓存策略
    feature_cache_ttl: 3600  # 1小时
    model_cache_ttl: 86400   # 24小时
    result_cache_ttl: 7200   # 2小时

# 监控配置
monitoring:
  # Prometheus指标
  prometheus:
    enabled: true
    host: "0.0.0.0"
    port: 9090
    metrics_path: "/metrics"
    
  # 健康检查
  health_check:
    enabled: true
    interval: 30  # 秒
    timeout: 10   # 秒
    
  # 指标收集间隔
  metrics_interval: 30  # 秒
  
  # 日志配置
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "listen_service.log"
    max_size: "100MB"
    backup_count: 5

# 集成配置
integration:
  # 与其他诊断服务的集成
  diagnostic_services:
    # 问诊服务
    inquiry_service:
      enabled: true
      host: "localhost"
      port: 50051
      timeout: 30
      
    # 望诊服务
    look_service:
      enabled: true
      host: "localhost"
      port: 50053
      timeout: 30
      
    # 切诊服务
    palpation_service:
      enabled: true
      host: "localhost"
      port: 50054
      timeout: 30
  
  # 与智能体的集成
  agents:
    # 小艾智能体
    xiaoai:
      enabled: true
      host: "localhost"
      port: 50061
      timeout: 60
      
    # 小克智能体
    xiaoke:
      enabled: true
      host: "localhost"
      port: 50062
      timeout: 60
      
    # 老克智能体
    laoke:
      enabled: true
      host: "localhost"
      port: 50063
      timeout: 60
      
    # 索儿智能体
    soer:
      enabled: true
      host: "localhost"
      port: 50064
      timeout: 60

# 安全配置
security:
  # TLS配置
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""
    
  # 认证配置
  authentication:
    enabled: false
    jwt_secret: ""
    token_expiry: 3600
    
  # 访问控制
  access_control:
    enabled: false
    allowed_ips: []
    rate_limit: 1000  # 每分钟请求数

# 性能调优
performance:
  # 线程池配置
  thread_pool:
    core_threads: 8
    max_threads: 32
    queue_size: 1000
    
  # 内存管理
  memory:
    max_heap_size: "4G"
    gc_strategy: "G1GC"
    
  # 网络优化
  network:
    tcp_nodelay: true
    tcp_keepalive: true
    socket_timeout: 30
    
  # 批处理优化
  batch_processing:
    max_batch_size: 16
    batch_timeout_ms: 100
    
# 开发和调试
development:
  debug_mode: false
  profile_enabled: false
  trace_enabled: false
  
  # 测试配置
  testing:
    mock_models: false
    test_data_path: "./test/data"
    
# 部署配置
deployment:
  environment: "production"  # development, staging, production
  
  # 容器配置
  container:
    memory_limit: "8G"
    cpu_limit: "4"
    
  # 扩展配置
  scaling:
    min_replicas: 2
    max_replicas: 10
    target_cpu_utilization: 70 