# A2A 智能体网络微服务配置

# 服务器配置
server:
  host: "0.0.0.0"
  port: 5000
  debug: false
  workers: 4
  max_connections: 1000

# 仪表板配置
dashboard:
  enabled: true
  host: "0.0.0.0"
  port: 5001
  debug: false

# 智能体配置
agents:
  xiaoai:
    name: "小艾智能体"
    url: "http://xiaoai-service:5001"
    timeout: 30
    retry_count: 3
    health_check_interval: 60
    capabilities:
      - "four_diagnoses_coordination"
      - "multimodal_input_processing"
      - "health_records_query"
      - "voice_interaction"
      - "accessibility_support"
  
  xiaoke:
    name: "小克智能体"
    url: "http://xiaoke-service:5002"
    timeout: 30
    retry_count: 3
    health_check_interval: 60
    capabilities:
      - "medical_resource_scheduling"
      - "product_customization"
      - "food_therapy_recommendation"
      - "blockchain_traceability"
      - "subscription_management"
  
  laoke:
    name: "老克智能体"
    url: "http://laoke-service:5003"
    timeout: 30
    retry_count: 3
    health_check_interval: 60
    capabilities:
      - "knowledge_content_management"
      - "learning_path_planning"
      - "community_content_management"
      - "tcm_knowledge_qa"
      - "content_recommendation"
  
  soer:
    name: "索儿智能体"
    url: "http://soer-service:5004"
    timeout: 30
    retry_count: 3
    health_check_interval: 60
    capabilities:
      - "personalized_health_plan"
      - "sensor_data_analysis"
      - "emotion_recognition"
      - "nutrition_analysis"
      - "health_companionship"

# 工作流配置
workflows:
  health_consultation:
    name: "健康咨询工作流"
    description: "用户健康咨询的完整处理流程"
    timeout: 300
    retry_count: 2
    steps:
      - id: "reception"
        agent: "xiaoai"
        action: "接收用户咨询"
        timeout: 30
      - id: "diagnosis_assessment"
        agent: "xiaoai"
        action: "诊断体质评估"
        timeout: 60
      - id: "knowledge_support"
        agent: "laoke"
        action: "提供知识支持"
        timeout: 45
      - id: "health_profile"
        agent: "soer"
        action: "生成健康画像"
        timeout: 60

  lifestyle_management:
    name: "生活方式工作流"
    description: "基于生活数据的健康管理流程"
    timeout: 240
    retry_count: 2
    steps:
      - id: "data_collection"
        agent: "soer"
        action: "数据采集接收"
        timeout: 30
      - id: "health_profile_analysis"
        agent: "soer"
        action: "健康画像分析"
        timeout: 60
      - id: "knowledge_support"
        agent: "laoke"
        action: "提供知识支持"
        timeout: 45
      - id: "comprehensive_response"
        agent: "soer"
        action: "综合回复"
        timeout: 45

  product_customization:
    name: "农产品定制工作流"
    description: "基于健康画像的个性化农产品定制流程"
    timeout: 300
    retry_count: 2
    steps:
      - id: "health_profile_input"
        agent: "soer"
        action: "健康画像输入"
        timeout: 30
      - id: "nutrition_analysis"
        agent: "xiaoke"
        action: "营养分析"
        timeout: 60
      - id: "knowledge_support"
        agent: "laoke"
        action: "知识支持"
        timeout: 45
      - id: "requirement_analysis"
        agent: "xiaoke"
        action: "需求分析"
        timeout: 45
      - id: "product_recommendation"
        agent: "xiaoke"
        action: "产品推荐"
        timeout: 60

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
  performance_metrics:
    - "request_count"
    - "request_duration"
    - "error_rate"
    - "agent_response_time"
    - "workflow_success_rate"
  
  alerts:
    enabled: true
    thresholds:
      error_rate: 0.05
      response_time: 5.0
      agent_offline_duration: 300

# 日志配置
logging:
  level: "INFO"
  format: "json"
  file: "logs/a2a-network.log"
  max_size: "100MB"
  backup_count: 5
  console_output: true

# 数据库配置 (可选)
database:
  enabled: false
  type: "mongodb"
  url: "mongodb://localhost:27017"
  name: "suoke_a2a_network"
  collections:
    workflows: "workflows"
    agents: "agents"
    metrics: "metrics"

# 安全配置
security:
  api_key_required: false
  cors_enabled: true
  cors_origins: ["*"]
  rate_limiting:
    enabled: true
    requests_per_minute: 100

# 性能配置
performance:
  connection_pool_size: 20
  request_timeout: 30
  max_concurrent_workflows: 50
  cache_enabled: true
  cache_ttl: 300 