# 索克生活健康数据服务默认配置

# 服务配置
service:
  name: "health-data-service"
  version: "1.0.0"
  description: "索克生活健康数据服务"

# 服务器配置
rest:
  host: "0.0.0.0"
  port: 8080
  workers: 1
  cors:
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
    allow_credentials: true
  timeout: 60  # 秒
  debug: false

# gRPC服务配置
grpc:
  host: "0.0.0.0"
  port: 50051
  max_workers: 10
  max_message_length: 104857600  # 100MB

# 数据库配置
database:
  dialect: "postgresql"
  driver: "asyncpg"
  host: "${DB_HOST:localhost}"
  port: "${DB_PORT:5432}"
  username: "${DB_USERNAME:postgres}"
  password: "${DB_PASSWORD:postgres}"
  database: "${DB_NAME:health_data}"
  pool_size: 5
  max_overflow: 10
  echo: false

# 区块链服务配置
blockchain:
  enabled: "${BLOCKCHAIN_ENABLED:false}"
  service_url: "${BLOCKCHAIN_SERVICE_URL:http://localhost:8081}"
  timeout: 30

# 监控配置
monitoring:
  prometheus:
    enabled: true
    port: 9180
  logging:
    level: "${LOG_LEVEL:INFO}"
    format: "json"
    output: ["console", "file"]
    file: "logs/health_data_service.log"
    rotation: "00:00"  # 每天轮换
    retention: "30 days"
    compression: "zip"

# 安全配置
security:
  jwt:
    enabled: true
    secret: "${JWT_SECRET:your-secret-key}"
    algorithm: "HS256"
    expires_in: 3600  # 秒
  api_cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
    max_age: 86400

# 缓存配置
cache:
  enabled: false
  type: "redis"
  url: "${REDIS_URL:redis://localhost:6379/0}"
  ttl: 3600  # 秒

# 数据分析配置
analytics:
  time_series:
    window_sizes: [7, 30, 90]  # 天
    aggregation_methods: ["mean", "max", "min", "sum"]
  correlation:
    min_data_points: 10
    significance_threshold: 0.05
  health_index:
    weights:
      heart_rate: 0.2
      steps: 0.15
      sleep: 0.25
      blood_pressure: 0.2
      blood_glucose: 0.1
      body_temperature: 0.05
      oxygen_saturation: 0.05
  tcm_constitution:
    model_path: "config/models/tcm_constitution_model.pkl"
    feature_weights_path: "config/models/tcm_feature_weights.json"

# 可穿戴设备数据配置
wearable_data:
  upload_limit: 10485760  # 10MB
  supported_devices:
    - name: "apple_health"
      parser: "apple_health_xml_parser"
    - name: "fitbit"
      parser: "fitbit_json_parser"
    - name: "garmin"
      parser: "garmin_fit_parser"
    - name: "xiaomi"
      parser: "xiaomi_json_parser"
  parsers:
    apple_health_xml_parser:
      supported_types: ["steps", "heart_rate", "sleep", "blood_pressure", "body_temperature"]
    fitbit_json_parser:
      supported_types: ["steps", "heart_rate", "sleep", "body_mass"]
    garmin_fit_parser:
      supported_types: ["steps", "heart_rate", "sleep", "activity"]
    xiaomi_json_parser:
      supported_types: ["steps", "heart_rate", "sleep"]

# 生物标记物分析配置
biometric_data:
  analysis:
    voice:
      enabled: true
      model_path: "models/voice_analysis.onnx"
    face:
      enabled: true
      model_path: "models/face_analysis.onnx"
    pulse:
      enabled: true
      model_path: "models/pulse_analysis.onnx"
    tongue:
      enabled: true
      model_path: "models/tongue_analysis.onnx"

# 健康数据模型
health_models:
  breathing:
    model_path: "models/breathing_analysis.onnx"
  stress:
    model_path: "models/stress_assessment.onnx"
  sleep:
    model_path: "models/sleep_quality.onnx"

# 数据归一化设置
normalization:
  heart_rate:
    max: 220
    min: 40
  steps:
    daily_target: 10000
  sleep:
    optimal_duration: 8
    min_duration: 4

# 数据导出设置
export:
  formats:
    - "json"
    - "csv"
    - "xml"
    - "pdf"
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"

# 隐私设置
privacy:
  data_retention:
    enabled: true
    period_days: 365
    exceptions:
      - "signed_consent"
      - "medical_records"
  anonymization:
    enabled: true
    methods:
      - "k-anonymity"
      - "l-diversity"
  consent_management:
    required: true
    validity_period_days: 365
    revocation_allowed: true

# 区块链集成设置
blockchain:
  enabled: true
  service_url: "${BLOCKCHAIN_SERVICE_URL:-http://blockchain-service:8008}"
  timeout: 10
  # 零知识证明相关设置
  zkp:
    enabled: true
    proof_types:
      - "health_index"
      - "condition_verification"
      - "medication_adherence"

# 微服务集成
integrations:
  rag_service:
    url: "${RAG_SERVICE_URL:-http://rag-service:8000}"
    grpc_port: 50051
    timeout: 5
  xiaoai_service:
    url: "${XIAOAI_SERVICE_URL:-http://xiaoai-service:8005}"
    grpc_port: 50055
    timeout: 5
  user_service:
    url: "${USER_SERVICE_URL:-http://user-service:8001}"
    grpc_port: 50052
    timeout: 5

# 消息队列
message_queue:
  enabled: false
  type: "rabbitmq"
  host: "${RABBITMQ_HOST:localhost}"
  port: "${RABBITMQ_PORT:5672}"
  username: "${RABBITMQ_USER:guest}"
  password: "${RABBITMQ_PASSWORD:guest}"
  vhost: "/"
  queues:
    health_data:
      name: "health_data"
      durable: true
      prefetch_count: 10
    analytics:
      name: "analytics"
      durable: true
      prefetch_count: 5

logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  file: "/app/logs/health-data-service.log"
  rotation: "500 MB"
  retention: "10 days"
  compression: "zip"

telemetry:
  enabled: "${TELEMETRY_ENABLED:-true}"
  exporter: "${TELEMETRY_EXPORTER:-prometheus}"
  endpoint: "${TELEMETRY_ENDPOINT:-http://prometheus:9090}"
  metrics:
    enabled: true
    prefix: "health_data"
    push_interval: 15  # 秒

# 熔断器配置
circuit_breaker:
  enabled: true
  failure_threshold: 5  # 失败次数阈值
  recovery_timeout: 30  # 恢复超时(秒)
  timeout: 10  # 操作超时(秒)
  max_retries: 3  # 最大重试次数 