# 统一知识服务配置

# 服务基本配置
service:
  name: "unified-knowledge-service"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000
  debug: false

# 数据库配置
database:
  primary:
    type: "postgresql"
    host: "${DB_HOST:-localhost}"
    port: "${DB_PORT:-5432}"
    database: "${DB_NAME:-unified_knowledge}"
    username: "${DB_USER:-postgres}"
    password: "${DB_PASSWORD:-password}"
    pool_size: 20
    max_overflow: 30
  
  document:
    type: "mongodb"
    host: "${MONGO_HOST:-localhost}"
    port: "${MONGO_PORT:-27017}"
    database: "${MONGO_DB:-knowledge_docs}"
    username: "${MONGO_USER:-}"
    password: "${MONGO_PASSWORD:-}"

# 缓存配置
cache:
  type: "redis"
  host: "${REDIS_HOST:-localhost}"
  port: "${REDIS_PORT:-6379}"
  database: "${REDIS_DB:-0}"
  password: "${REDIS_PASSWORD:-}"
  ttl: 3600

# 医学知识模块配置
med_knowledge:
  data_path: "data/knowledge"
  index_path: "data/knowledge/index"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  max_search_results: 100
  similarity_threshold: 0.7

# 基准测试模块配置
benchmark:
  data_path: "data/benchmark"
  results_path: "data/benchmark/results"
  test_timeout: 300
  parallel_tests: 4
  report_format: ["json", "html", "pdf"]

# API配置
api:
  rate_limit: "100/minute"
  max_request_size: "10MB"
  timeout: 30

# CORS配置
cors:
  origins: ["*"]
  methods: ["GET", "POST", "PUT", "DELETE"]
  headers: ["*"]

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/unified-knowledge-service.log"
  max_size: "100MB"
  backup_count: 5

# 监控配置
monitoring:
  metrics_enabled: true
  health_check_interval: 30
  performance_tracking: true
