apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: accessibility-service
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENABLE_PROFILING
          value: "false"
        - name: USE_CACHE
          value: "true"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: accessibility-service 