# 无障碍服务配置
accessibility:
  # 服务启用状态
  enabled: true
  
  # 无障碍服务地址
  service_url: "http://localhost:50051"
  
  # gRPC服务地址
  grpc_url: "localhost:50051"
  
  # 请求超时时间（秒）
  timeout: 30
  
  # 最大重试次数
  max_retries: 3
  
  # 支持的功能
  features:
    voice_assistance: true      # 语音辅助
    image_assistance: true      # 图像辅助
    screen_reading: true        # 屏幕阅读
    content_generation: true    # 内容生成
    speech_translation: true    # 语音翻译
    sign_language: true         # 手语识别
    
  # 默认设置
  defaults:
    language: "zh-CN"
    voice_type: "female"
    speech_rate: 1.0
    high_contrast: false
    screen_reader: true
    font_size: "medium"
    
  # 健康检查配置
  health_check:
    enabled: true
    interval: 60  # 秒
    timeout: 5    # 秒
    
  # 日志配置
  logging:
    level: "INFO"
    log_requests: true
    log_responses: false  # 避免记录敏感音频数据 