apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-data
  namespace: suoke-core
  labels:
    app: user-service
    app.kubernetes.io/part-of: suoke-life
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 