{
 "title": "小克服务(XiaoKeService)监控面板",
 "tags": [
  "xiaoke-service",
  "grpc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(up{job=\"xiaoke-service\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "服务概况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "活跃实例",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"xiaoke-service\"})"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(xiaoke_grpc_request_errors_total{job=\"xiaoke-service\"}[5m])) / sum(rate(xiaoke_grpc_requests_total{job=\"xiaoke-service\"}[5m]))"
    }
   ]
  },
  {
   "title": "请求速率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(xiaoke_grpc_requests_total{job=\"xiaoke-service\"}[5m]))"
    }
   ]
  },
  {
   "title": "95% 延迟",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xiaoke_grpc_request_duration_seconds_bucket{job=\"xiaoke-service\"}[5m])) by (le))"
    }
   ]
  },
  { "title": "系统资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"xiaoke-service-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"xiaoke-service-.*\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "API性能", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "每秒请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xiaoke_grpc_requests_total{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "每秒错误数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xiaoke_grpc_request_errors_total{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "请求延迟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(xiaoke_grpc_request_duration_seconds_bucket{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (le, method))",
     "legendFormat": "{{method}} p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(xiaoke_grpc_request_duration_seconds_bucket{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (le, method))",
     "legendFormat": "{{method}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(xiaoke_grpc_request_duration_seconds_bucket{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (le, method))",
     "legendFormat": "{{method}} p99"
    }
   ]
  },
  { "title": "ERP集成", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "ERP API调用速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xiaoke_erp_requests_total{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ERP API错误",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xiaoke_erp_request_errors_total{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ERP API 95% 响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xiaoke_erp_request_duration_seconds_bucket{job=\"xiaoke-service\", instance=~\"$instance\"}[5m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}