apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.suoke.life/suoke/api-gateway.git'
    path: k8s/overlays/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: suoke
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 