apiVersion: v1
kind: ConfigMap
metadata:
  name: suoke-config
  namespace: suoke-staging
  labels:
    app: suoke-life
    environment: staging
data:
  # 应用配置
  ENVIRONMENT: "staging"
  LOG_LEVEL: "DEBUG"
  DEBUG: "true"
  
  # 服务端口配置
  API_GATEWAY_PORT: "8000"
  USER_SERVICE_PORT: "8001"
  HEALTH_DATA_SERVICE_PORT: "8002"
  
  # 数据库配置
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "suoke_staging"
  
  # Redis配置
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # 外部服务配置
  CORS_ORIGINS: "*"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_DEFAULT_RATE: "1000/minute"
  
  # JWT配置
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # 监控配置
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # AI服务配置
  AI_MODEL_TIMEOUT: "30"
  AI_MODEL_RETRIES: "3"
  
  # 中医诊断配置
  TCM_DIAGNOSIS_ENABLED: "true"
  TCM_MODEL_VERSION: "v1.0"
  
  # 文件存储配置
  UPLOAD_MAX_SIZE: "10485760"  # 10MB
  UPLOAD_ALLOWED_TYPES: "image/jpeg,image/png,image/gif,application/pdf" 