apiVersion: v1
kind: Secret
metadata:
  name: suoke-secrets
  namespace: suoke-staging
  labels:
    app: suoke-life
    environment: staging
type: Opaque
data:
  # 数据库密码 (base64编码)
  DB_PASSWORD: c3Vva2VfcGFzc3dvcmQ=  # suoke_password
  
  # JWT密钥 (base64编码)
  JWT_SECRET_KEY: c3Vva2Vfandfc2VjcmV0X2tleV9zdGFnaW5n  # suoke_jwt_secret_key_staging
  
  # Redis密码 (base64编码)
  REDIS_PASSWORD: ""  # 空密码
  
  # API密钥 (base64编码)
  API_SECRET_KEY: c3Vva2VfYXBpX3NlY3JldF9rZXlfc3RhZ2luZw==  # suoke_api_secret_key_staging
  
  # 外部服务API密钥
  OPENAI_API_KEY: ""  # 需要在部署时设置
  BAIDU_API_KEY: ""   # 需要在部署时设置
  ALIYUN_ACCESS_KEY: ""  # 需要在部署时设置
  ALIYUN_SECRET_KEY: ""  # 需要在部署时设置
  
  # 区块链配置
  BLOCKCHAIN_PRIVATE_KEY: ""  # 需要在部署时设置
  BLOCKCHAIN_NETWORK_URL: ""  # 需要在部署时设置
  
  # 消息队列配置
  RABBITMQ_URL: ""  # 需要在部署时设置
  
  # 监控配置
  PROMETHEUS_TOKEN: ""  # 需要在部署时设置
  GRAFANA_API_KEY: ""   # 需要在部署时设置 