apiVersion: v1
kind: ServiceAccount
metadata:
  name: inquiry-diagnosis-service-account
  namespace: suoke
  labels:
    app: inquiry-diagnosis
    service: four-diagnosis
  annotations:
    vault.hashicorp.com/role: "inquiry-diagnosis-service-role" 