apiVersion: apps/v1
kind: Deployment
metadata:
  name: suoke-api-gateway
  labels:
    app: suoke-api-gateway
    component: gateway
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: suoke-api-gateway
  template:
    metadata:
      labels:
        app: suoke-api-gateway
        component: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: suoke-api-gateway
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: api-gateway
        image: suoke/suoke-api-gateway:latest
        imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          protocol: TCP
        - name: grpc
          containerPort: 50051
          protocol: TCP
          env:
        - name: ENVIRONMENT
          value: "production"
            - name: LOG_LEVEL
              value: "INFO"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: GRPC_HOST
          value: "0.0.0.0"
        - name: GRPC_PORT
          value: "50051"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: suoke-api-gateway-secrets
              key: jwt-secret-key
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: CORS_ORIGINS
          value: "*"
        - name: RATE_LIMIT_ENABLED
          value: "true"
        - name: RATE_LIMIT_DEFAULT_RATE
          value: "100/minute"
        - name: TRACING_ENABLED
          value: "true"
        - name: TRACING_JAEGER_ENDPOINT
          value: "http://jaeger-collector:14268/api/traces"
        - name: METRICS_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: suoke-api-gateway-config
        - secretRef:
            name: suoke-api-gateway-secrets
          resources:
            requests:
            memory: "256Mi"
            cpu: "250m"
            limits:
            memory: "512Mi"
            cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          periodSeconds: 10
            timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
          initialDelaySeconds: 10
            periodSeconds: 5
          timeoutSeconds: 3
            failureThreshold: 30
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: logs
          mountPath: /app/logs
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
          configMap:
          name: suoke-api-gateway-config
      - name: logs
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst 