
apiVersion: v1
kind: Namespace
metadata:
  name: suoke-life
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-knowledge-service
  namespace: suoke-life
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unified-knowledge-service
  template:
    metadata:
      labels:
        app: unified-knowledge-service
    spec:
      containers:
      - name: unified-knowledge-service
        image: suoke/unified-knowledge-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: unified-knowledge-service
  namespace: suoke-life
spec:
  selector:
    app: unified-knowledge-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
