# frozen_string_literal: true

# 使用清华源来加速 CocoaPods 依赖下载
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

# ENV['COCOAPODS_DISABLE_GITHUB_PROXY'] = 'true'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SuokeLife' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for fmt library compilation error with newer Xcode versions
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_PEDANTIC'] = 'NO'
          config.build_settings['WARNING_CFLAGS'] = '$(inherited) -w'
          config.build_settings['OTHER_CFLAGS'] = '$(inherited) -w -DFMT_HEADER_ONLY=1 -DFMT_DISABLE_COMPILE_TIME_CHECKS'
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config.build_settings['CLANG_WARN_EVERYTHING'] = 'NO'
          config.build_settings['CLANG_WARN_PEDANTIC'] = 'NO'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -w -DFMT_HEADER_ONLY=1'
        end
      end
      
      # 设置iOS部署目标为12.4
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  end
end
