apiVersion: apps/v1
kind: Deployment
metadata:
  name: human-review-service
  namespace: suoke-life
  labels:
    app: human-review-service
    version: v1.0.0
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: human-review-service
  template:
    metadata:
      labels:
        app: human-review-service
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: human-review-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: human-review-service
        image: suoke-life/human-review-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: APP_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: human-review-service-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: human-review-service-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: human-review-service-secrets
              key: secret-key
        - name: NOTIFICATION_EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: human-review-service-config
              key: email-host
        - name: NOTIFICATION_EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: human-review-service-config
              key: email-port
        - name: NOTIFICATION_EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: human-review-service-secrets
              key: email-username
        - name: NOTIFICATION_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: human-review-service-secrets
              key: email-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: logs
        emptyDir: {}
      - name: config
        configMap:
          name: human-review-service-config
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - human-review-service
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: human-review-service
  namespace: suoke-life
  labels:
    app: human-review-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: human-review-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: human-review-service-config
  namespace: suoke-life
data:
  app-name: "索克生活人工审核微服务"
  app-version: "1.0.0"
  debug: "false"
  log-level: "INFO"
  
  # 数据库配置
  database-pool-size: "10"
  database-max-overflow: "20"
  database-pool-timeout: "30"
  database-pool-recycle: "3600"
  
  # Redis配置
  redis-max-connections: "100"
  redis-retry-on-timeout: "true"
  redis-socket-keepalive: "true"
  redis-socket-keepalive-options: "1,3,5"
  
  # 审核配置
  review-default-timeout: "3600"
  review-max-concurrent-tasks: "10"
  review-auto-assignment: "true"
  review-priority-weights: "critical:5,urgent:4,high:3,normal:2,low:1"
  
  # 通知配置
  email-host: "smtp.example.com"
  email-port: "587"
  email-use-tls: "true"
  email-from-address: "noreply@suoke-life.com"
  
  # 监控配置
  monitoring-enabled: "true"
  monitoring-metrics-path: "/metrics"
  monitoring-health-path: "/health"
  
  # 安全配置
  security-algorithm: "HS256"
  security-access-token-expire-minutes: "30"
  security-refresh-token-expire-days: "7"

---
apiVersion: v1
kind: Secret
metadata:
  name: human-review-service-secrets
  namespace: suoke-life
type: Opaque
data:
  # 注意：这些值需要base64编码
  # 实际部署时应该使用外部密钥管理系统
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDpwb3J0L2RiX25hbWU=
  redis-url: cmVkaXM6Ly9ob3N0OnBvcnQvMA==
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=
  email-username: eW91ci1lbWFpbC11c2VybmFtZQ==
  email-password: eW91ci1lbWFpbC1wYXNzd29yZA==

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: human-review-service
  namespace: suoke-life
  labels:
    app: human-review-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: human-review-service
  namespace: suoke-life
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.suoke-life.com
    secretName: human-review-service-tls
  rules:
  - host: api.suoke-life.com
    http:
      paths:
      - path: /human-review
        pathType: Prefix
        backend:
          service:
            name: human-review-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: human-review-service
  namespace: suoke-life
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: human-review-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60 