version: '3.8'

services:
  corn-maze-service:
    build:
      context: ..
      dockerfile: Dockerfile
    image: corn-maze-service:latest
    container_name: corn-maze-service
    restart: unless-stopped
    ports:
      - "50057:50057"  # gRPC端口
      - "51057:51057"  # 指标端口
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=DEBUG
      - GRPC_PORT=50057
      - METRICS_PORT=51057
      - DB_PATH=/app/data/maze.db
    volumes:
      - ../config:/app/config
      - ../data:/app/data
      - ../logs:/app/logs
    networks:
      - suoke-net
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket().connect(('localhost', 50057))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 开发用的数据查看工具
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SQLITE_DATABASE=/data/maze.db
    volumes:
      - ../data:/data
    networks:
      - suoke-net
    depends_on:
      - corn-maze-service

networks:
  suoke-net:
    driver: bridge