"""
xiaoai_pb2 - 索克生活项目模块
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xiaoai.proto
"""Generated protocol buffer code."""
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cxiaoai.proto\x12\x06xiaoai\"\x8d\x01\n\x18IntegrateDiagnosisRequest\x12\x14\n\x0cinquiry_data\x18\x01 \x01(\t\x12\x11\n\tlook_data\x18\x02 \x01(\t\x12\x13\n\x0blisten_data\x18\x03 \x01(\t\x12\x17\n\x0fpalpation_data\x18\x04 \x01(\t\x12\x1a\n\x12integration_result\x18\x05 \x01(\t\"O\n\x19IntegrateDiagnosisResponse\x12\x1a\n\x12integration_result\x18\x01 \x01(\t\x12\x16\n\nconfidence\x18\x02 \x01(\x02:\x02\x30\x35\"M\n\x1aConstitutionAnalysisRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08symptoms\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"Q\n\x1bConstitutionAnalysisResponse\x12\x18\n\x10\x61nalysis_result\x18\x01 \x01(\t\x12\x18\n\nconfidence\x18\x02 \x01(\x02:\x04\x30.75\x32\xc3\x01\n\x0cXiaoAIService\x12`\n\x15IntegrateFourDiagnosis\x12 .xiaoai.IntegrateDiagnosisRequest\x1a!.xiaoai.IntegrateDiagnosisResponse\"\x00\x30\x01\x12Q\n\x12\x41nalyzeConstitution\x12\".xiaoai.ConstitutionAnalysisRequest\x1a\x17.xiaoai.ConstitutionAnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xiaoai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTEGRATEDIAGNOSISREQUEST']._serialized_start=25
  _globals['_INTEGRATEDIAGNOSISREQUEST']._serialized_end=166
  _globals['_INTEGRATEDIAGNOSISRESPONSE']._serialized_start=168
  _globals['_INTEGRATEDIAGNOSISRESPONSE']._serialized_end=247
  _globals['_CONSTITUTIONANALYSISREQUEST']._serialized_start=249
  _globals['_CONSTITUTIONANALYSISREQUEST']._serialized_end=326
  _globals['_CONSTITUTIONANALYSISRESPONSE']._serialized_start=328
  _globals['_CONSTITUTIONANALYSISRESPONSE']._serialized_end=409
  _globals['_XIAOAISERVICE']._serialized_start=412
  _globals['_XIAOAISERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)