version: '3.8'

services:
  laoke-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: suoke/laoke-service:latest
    container_name: laoke-service
    restart: unless-stopped
    ports:
      - "8080:8080"     # GraphQL API端口
      - "50051:50051"   # gRPC 服务端口
      - "51051:51051"   # Prometheus 指标端口
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - SERVICE_ENV=production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-laokepassword}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-laokepassword}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-laokepassword}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-laokepassword}
      - LLM_API_KEY=${LLM_API_KEY:-}
    depends_on:
      - mongodb
      - postgres
      - redis
      - neo4j
    networks:
      - suoke-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  # Neo4j 图数据库
  neo4j:
    image: neo4j:5.18-community
    container_name: laoke-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./config/neo4j.conf:/conf/neo4j.conf
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-laokepassword}
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
    networks:
      - suoke-network
    deploy:
      resources:
        limits:
          memory: 2G

  # MongoDB 数据库
  mongodb:
    image: mongo:6.0
    container_name: laoke-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD:-adminpassword}
      - MONGO_INITDB_DATABASE=laoke_db
    command: ["--auth", "--bind_ip_all"]
    networks:
      - suoke-network
    deploy:
      resources:
        limits:
          memory: 1G

  # PostgreSQL 数据库
  postgres:
    image: postgres:15
    container_name: laoke-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
    environment:
      - POSTGRES_USER=laoke
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-laokepassword}
      - POSTGRES_DB=laoke_db
    networks:
      - suoke-network
    deploy:
      resources:
        limits:
          memory: 1G

  # Redis 缓存
  redis:
    image: redis:7.0-alpine
    container_name: laoke-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD:-laokepassword}"]
    networks:
      - suoke-network
    deploy:
      resources:
        limits:
          memory: 512M

  # Prometheus 监控
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: laoke-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./deploy/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - suoke-network
    deploy:
      resources:
        limits:
          memory: 512M

  # Grafana 仪表盘
  grafana:
    image: grafana/grafana:10.0.3
    container_name: laoke-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    networks:
      - suoke-network
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  suoke-network:
    name: suoke-network
    external: true

volumes:
  neo4j_data:
  neo4j_logs:
  mongodb_data:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: 