apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke

commonLabels:
  environment: production
  app: auth-service

resources:
- ../../base
- ../../backup-cronjob.yaml
- ../../backup-pvc.yaml
- ../../backup-verify-cronjob.yaml
- ../../key-rotation.yaml
- ../../vault-secretprovider.yaml

# 生产环境设置
patches:
- path: resources-patch.yaml
  target:
    kind: Deployment
    name: auth-service
- path: pod-topology-patch.yaml
  target:
    kind: Deployment
    name: auth-service

# 镜像覆盖
images:
- name: auth-service
  newName: suoke-registry.cn-hangzhou.cr.aliyuncs.com/suoke/auth-service
  newTag: stable

replicas:
- name: auth-service
  count: 3