# 小克服务配置文件

# 服务配置
service:
  name: xiaoke-service
  version: 1.0.0
  description: 小克服务 - 医疗资源调度平台
  
# 服务器配置
server:
  grpc:
    host: 0.0.0.0
    port: 50054
    max_workers: 10
    max_message_length: 10485760  # 10MB
  
  monitoring:
    host: 0.0.0.0
    port: 51054
    metrics_path: /metrics
    
# 数据库配置
database:
  postgres:
    host: ${POSTGRES_HOST:-postgres}
    port: ${POSTGRES_PORT:-5432}
    database: ${POSTGRES_DB:-xiaoke_db}
    user: ${POSTGRES_USER:-xiaoke}
    password: ${POSTGRES_PASSWORD}
    pool_size: 10
    max_overflow: 20
    
  mongodb:
    uri: mongodb://${MONGO_USER:-xiaoke}:${MONGO_PASSWORD}@${MONGO_HOST:-mongodb}:${MONGO_PORT:-27017}/${MONGO_DB:-xiaoke_db}?authSource=admin
    database: ${MONGO_DB:-xiaoke_db}
    
  redis:
    host: ${REDIS_HOST:-redis}
    port: ${REDIS_PORT:-6379}
    db: 0
    password: ${REDIS_PASSWORD}
    
# 外部服务配置
external_services:
  erp:
    api_url: ${ERP_API_URL:-https://erp-api.suoke.life}
    api_key: ${ERP_API_KEY}
    timeout: 30
    
  payment:
    gateway_url: ${PAYMENT_GATEWAY_URL:-https://payment-api.suoke.life}
    api_key: ${PAYMENT_GATEWAY_API_KEY}
    timeout: 30
    
  blockchain:
    node_url: ${BLOCKCHAIN_NODE_URL:-https://ethereum.infura.io/v3/your_api_key}
    api_key: ${BLOCKCHAIN_API_KEY}
    contract_address: ${BLOCKCHAIN_CONTRACT_ADDRESS:-0x0000000000000000000000000000000000000000}
    
  logistics:
    api_url: ${LOGISTICS_API_URL:-https://logistics-api.suoke.life}
    api_key: ${LOGISTICS_API_KEY}
    timeout: 30
    
# 调度算法配置
scheduler:
  resource_matching:
    # 资源匹配算法权重配置
    weights:
      constitution_match: 0.4    # 体质匹配权重
      location_proximity: 0.2    # 地理位置接近度权重
      rating: 0.2                # 评分权重
      availability: 0.2          # 可用性权重
    
    # 最大建议结果数
    max_recommendations: 5
    
# 推荐系统配置
recommendation:
  # 产品推荐算法配置
  product:
    # 推荐算法权重配置
    weights:
      constitution_match: 0.35    # 体质匹配权重
      season_match: 0.25          # 季节匹配权重
      user_preference: 0.25       # 用户偏好权重
      health_condition: 0.15      # 健康状况权重
      
    min_confidence_threshold: 0.6  # 最小置信度阈值
    max_recommendations: 10        # 最大推荐结果数
    
# 日志配置
logging:
  level: ${LOG_LEVEL:-INFO}
  format: ${LOG_FORMAT:-text}  # text 或 json
  file: ${LOG_FILE:-logs/xiaoke-service.log}
  
# 监控配置
monitoring:
  enabled: ${MONITORING_ENABLED:-true}
  prometheus:
    enabled: true
    push_gateway: ${PROMETHEUS_PUSH_GATEWAY:-}  # 为空则不推送
  
  tracing:
    enabled: ${TRACING_ENABLED:-false}
    jaeger:
      host: ${JAEGER_HOST:-jaeger}
      port: ${JAEGER_PORT:-6831}
      
# 安全配置
security:
  # API密钥有效期（秒）
  api_key_ttl: 3600
  
  # 用于加密敏感数据的密钥（应通过环境变量传递）
  encryption_key: ${ENCRYPTION_KEY}
  
  # 跨服务认证
  service_auth:
    enabled: true
    auth_header: X-Service-Auth
    token_secret: ${SERVICE_AUTH_SECRET}
    
# 特性开关
feature_flags:
  blockchain_tracing: ${FEATURE_BLOCKCHAIN_TRACING:-true}
  ai_recommendations: ${FEATURE_AI_RECOMMENDATIONS:-true}
  advanced_scheduling: ${FEATURE_ADVANCED_SCHEDULING:-true}