# 小克智能体服务默认配置
service:
  name: xiaoke-service
  version: 1.0.0
  description: 索克生活APP的医疗资源调度智能体

server:
  host: 0.0.0.0
  port: 8080
  debug: false
  workers: 4
  timeout: 60
  cors:
    enabled: true
    origins:
      - "*"

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/xiaoke-service.log
  max_size: 10485760  # 10MB
  backup_count: 5

metrics:
  enabled: true
  report_interval: 60  # 秒

conversation:
  system_prompt: "你是小克，索克生活APP的医疗资源调度智能体，你专注于医疗资源调度、治疗计划制定和药物管理。"
  max_history_turns: 20

models:
  llm:
    primary_model: gpt-4o-mini
    fallback_model: llama-3-8b
    api_key: ${OPENAI_API_KEY}
    api_base: ${OPENAI_API_BASE:-https://api.openai.com/v1}
    org_id: ${OPENAI_ORG_ID}
    timeout: 60
  
  local_llm:
    endpoint_url: http://localhost:8000/v1
    available_models:
      - llama-3-8b
      - llama-3-70b
    default_model: llama-3-8b
    max_tokens: 4096
  
  zhipu:
    api_key: ${ZHIPU_API_KEY}
    available_models:
      - glm-4
      - glm-3-turbo
  
  baidu:
    api_key: ${BAIDU_API_KEY}
    secret_key: ${BAIDU_SECRET_KEY}
    api_url: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/
    available_models:
      - ernie-bot-4
      - ernie-bot

database:
  type: postgresql
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  username: ${DB_USER:-postgres}
  password: ${DB_PASS:-postgres}
  database: ${DB_NAME:-xiaoke_service}
  pool_size: 10
  max_overflow: 5
  timeout: 30

cache:
  type: redis
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}
  db: 0
  password: ${REDIS_PASS}
  ttl: 3600

queues:
  message_bus:
    host: ${KAFKA_HOST:-localhost}
    port: ${KAFKA_PORT:-9092}
    topic_prefix: xiaoke
    consumer_group: xiaoke-service
    topics:
      - medical-resources
      - treatment-plans
      - medicines

integrations:
  med_knowledge:
    url: ${MED_KNOWLEDGE_URL:-http://localhost:8081}
    api_key: ${MED_KNOWLEDGE_KEY}
  
  hospital_system:
    url: ${HOSPITAL_SYSTEM_URL}
    api_key: ${HOSPITAL_SYSTEM_KEY}
    timeout: 30

security:
  jwt:
    secret: ${JWT_SECRET}
    algorithm: HS256
    expires: 3600  # 1小时
  
  api_keys:
    enabled: true
    header_name: X-API-Key

resilience:
  circuit_breaker:
    failure_threshold: 5
    recovery_time: 30
  
  rate_limiter:
    max_calls: 60
    time_period: 60