{{- if .Values.istio.enabled }}
{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "common.names.fullname" . }}-destination-rule
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "auth-service"
spec:
  host: {{ include "common.names.fullname" . }}
  trafficPolicy:
    {{- if .Values.istio.destinationRule.trafficPolicy.connectionPool }}
    connectionPool:
      {{- if .Values.istio.destinationRule.trafficPolicy.connectionPool.tcp }}
      tcp:
        {{- toYaml .Values.istio.destinationRule.trafficPolicy.connectionPool.tcp | nindent 8 }}
      {{- end }}
      {{- if .Values.istio.destinationRule.trafficPolicy.connectionPool.http }}
      http:
        {{- toYaml .Values.istio.destinationRule.trafficPolicy.connectionPool.http | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.istio.destinationRule.trafficPolicy.outlierDetection }}
    outlierDetection:
      {{- toYaml .Values.istio.destinationRule.trafficPolicy.outlierDetection | nindent 6 }}
    {{- end }}
    {{- if .Values.istio.destinationRule.trafficPolicy.tls }}
    tls:
      mode: {{ .Values.istio.destinationRule.trafficPolicy.tls.mode }}
    {{- end }}
{{- end }}
{{- end }} 