{{- $fullName := include "common.names.fullname" . -}}
{{- if .Values.persistentVolume.logs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-logs
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "auth-service"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- range .Values.persistentVolume.logs.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.logs.size | quote }}
  storageClassName: {{ .Values.persistentVolume.logs.storageClass }}
{{- end }}

{{- if .Values.persistentVolume.config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "auth-service"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- range .Values.persistentVolume.config.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.config.size | quote }}
  storageClassName: {{ .Values.persistentVolume.config.storageClass }}
{{- end }} 