apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "auth-service"
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.stringData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }} 