service:
  name: accessibility-service
  version: 0.2.0
  host: 0.0.0.0
  port: 50051
  data_root: /var/lib/accessibility-service

models:
  scene_model: microsoft/beit-base-patch16-224-pt22k
  sign_language_model: mediapipe/hands
  speech_model:
    asr: silero-models/silero-stt-model
    tts: silero-models/silero-tts-model
  conversion_model: google/flan-t5-base

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: /var/log/accessibility-service/service.log

database:
  host: localhost
  port: 5432
  name: accessibility_db
  user: accessibility_user
  password: ${ACCESSIBILITY_DB_PASSWORD}  # 生产环境中使用环境变量

features:
  blind_assistance:
    enabled: true
    max_image_size: 1024
    confidence_threshold: 0.7
    obstacle_detection:
      max_distance: 10  # 最大检测距离（米）
      min_confidence: 0.6  # 最小置信度

  sign_language:
    enabled: true
    supported_languages:
      - zh-CN
      - en-US
    model_options:
      min_detection_confidence: 0.7
      min_tracking_confidence: 0.5

  screen_reading:
    enabled: true
    element_detection_threshold: 0.6
    ocr_conf_threshold: 0.7
    highlight_elements: true
    auto_scroll: true

  voice_assistance:
    enabled: true
    supported_dialects:
      - mandarin  # 普通话
      - cantonese  # 粤语
      - sichuanese  # 四川话
      - shanghainese  # 上海话
      - hokkien  # 闽南话
      - hakka  # 客家话
      - northeastern  # 东北话
      - northwestern  # 西北话
      - tibetan  # 藏语
      - uighur  # 维吾尔语
      - mongolian  # 蒙古语
      - zhuang  # 壮语
      - korean  # 朝鲜语
      - kazakh  # 哈萨克语
    asr_options:
      sample_rate: 16000
      timeout_seconds: 30

  content_conversion:
    enabled: true
    supported_formats:
      - audio
      - simplified
      - braille
    simplification_level: 2  # 1-3，3为最简化

# 新增后台数据采集服务配置
background_collection:
  enabled: true
  collection_types:
    pulse:
      enabled: true
      interval_seconds: 60
      privacy_level: high
      display_name: "脉搏数据"
    sleep:
      enabled: true
      interval_seconds: 300
      privacy_level: medium
      display_name: "睡眠数据"
    activity:
      enabled: true
      interval_seconds: 120
      privacy_level: low
      display_name: "活动数据"
    environment:
      enabled: true
      interval_seconds: 600
      privacy_level: low
      display_name: "环境数据"
    voice:
      enabled: true
      interval_seconds: 1800
      privacy_level: high
      display_name: "声音特征数据"
  sync:
    interval_minutes: 15
    retry_count: 3
    batch_size: 50
  consent:
    require_explicit: true
    default_expiry_days: 365
    revocable: true
    privacy_policy_url: "https://suoke-life.com/privacy/background-collection"
  battery_optimization:
    low_power_mode:
      enabled: true
      collection_types:
        - pulse
        - sleep
    idle_detection:
      enabled: true
      idle_threshold_minutes: 30
  notification:
    show_collection_status: true
    periodic_reminder: false
    reminder_interval_days: 30

# 新增边缘计算服务配置
edge_computing:
  enabled: true
  models:
    scene_detection_lite: models/edge/scene_detection_lite.tflite
    hand_gesture_lite: models/edge/hand_gesture_lite.tflite
    text_recognition_lite: models/edge/text_recognition_lite.tflite
  offline_mode:
    enabled: true
    features:
      - basic_scene_recognition
      - simple_hand_gestures
      - local_text_recognition
    max_cache_size_mb: 200
  sync:
    interval_hours: 24
    bandwidth_limit_kbps: 500

# 新增智能体协作服务配置
agent_coordination:
  event_bus:
    type: pulsar  # pulsar, kafka, memory
    connection:
      broker_url: pulsar://localhost:6650
      topic_prefix: accessibility
      subscription: accessibility-service

# 新增观测性服务配置
observability:
  metrics:
    provider: prometheus  # prometheus, datadog, memory
    endpoint: /metrics
    push_gateway: http://prometheus-pushgateway:9091
    interval_seconds: 60
    labels:
      environment: ${ENV:-development}
      version: ${VERSION:-0.2.0}
  tracing:
    provider: opentelemetry  # opentelemetry, jaeger, memory
    endpoint: http://jaeger-collector:14268/api/traces
    service_name: accessibility-service
    sample_rate: 0.1
  logging:
    provider: fluent-bit  # fluent-bit, elasticsearch, stdout
    forward_address: localhost:24224
    structured: true

# 新增安全与隐私配置
security:
  encryption:
    data_at_rest:
      algorithm: AES-256-GCM
      key_rotation_days: 90
    data_in_transit:
      tls_version: TLSv1.3
  access_control:
    authentication:
      jwt_issuer: accessibility-service
      token_expiry_minutes: 60
    authorization:
      rbac_enabled: true
      default_deny: true
      rules_path: /etc/accessibility-service/rbac_rules.yaml
  privacy:
    data_retention:
      user_data_days: 90
      log_data_days: 30
    consent_management:
      consent_expiry_days: 365
      required_for_features:
        - blind_assistance
        - sign_language

# 新增容灾备份配置
resilience:
  backup:
    enabled: true
    path: /var/backups/accessibility-service
    max_backups: 5
    backup_items:
      - /var/lib/accessibility-service/data
      - /var/lib/accessibility-service/models
      - /etc/accessibility-service
    schedule:
      daily:
        frequency: daily
        time: "02:00"
        type: incremental
      weekly:
        frequency: weekly
        time: "03:00"
        type: full

integration:
  xiaoai_service:  # 小艾服务 - 四诊协调引擎
    host: xiaoai-service
    port: 50052
    timeout_ms: 5000
    retry: 3

  xiaoke_service:  # 小克服务 - 医疗资源调度
    host: xiaoke-service
    port: 50053
    timeout_ms: 5000
    retry: 3

  laoke_service:  # 老克服务 - 知识传播平台
    host: laoke-service
    port: 50054
    timeout_ms: 5000
    retry: 3

  soer_service:  # 索儿服务 - 健康管理引擎
    host: soer-service
    port: 50055
    timeout_ms: 5000
    retry: 3

# 无障碍特性支持级别（可供前端配置使用）
accessibility_levels:
  basic:  # 基础无障碍支持
    - screen_reading
    - voice_assistance
    - high_contrast
    - text_resize
  
  intermediate:  # 中级无障碍支持
    - blind_assistance
    - simplified_content
    - dialect_support
    - tcm_accessibility
  
  advanced:  # 高级无障碍支持
    - sign_language
    - braille_output
    - full_voice_control
    - edge_computing
    - multi_dialect 