service:
  name: accessibility-service
  version: 0.2.0
  host: 0.0.0.0
  port: 50051
  data_root: ${HOME}/data/accessibility-service

models:
  scene_model: microsoft/beit-base-patch16-224-pt22k
  sign_language_model: mediapipe/hands
  speech_model:
    asr: silero-models/silero-stt-model
    tts: silero-models/silero-tts-model
  conversion_model: google/flan-t5-base

logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: ${HOME}/logs/accessibility-service/service.log

database:
  host: localhost
  port: 5432
  name: accessibility_db
  user: accessibility_user
  password: password  # 开发环境使用，生产环境应使用环境变量

features:
  blind_assistance:
    enabled: false
    max_image_size: 1024
    confidence_threshold: 0.7
    obstacle_detection:
      max_distance: 10  # 最大检测距离（米）
      min_confidence: 0.6  # 最小置信度

  sign_language:
    enabled: true
    supported_languages:
      - zh-CN
      - en-US
    model_options:
      min_detection_confidence: 0.7
      min_tracking_confidence: 0.5

  screen_reading:
    enabled: true
    element_detection_threshold: 0.6
    ocr_conf_threshold: 0.7
    highlight_elements: true
    auto_scroll: true

  voice_assistance:
    enabled: true
    supported_dialects:
      - mandarin  # 普通话
      - cantonese  # 粤语
      - sichuanese  # 四川话
    asr_options:
      sample_rate: 16000
      timeout_seconds: 30

  content_conversion:
    enabled: true
    supported_formats:
      - audio
      - simplified
    simplification_level: 2  # 1-3，3为最简化

# 后台数据采集服务配置 - 开发环境简化版
background_collection:
  enabled: false

# 边缘计算服务配置 - 开发环境简化版
edge_computing:
  enabled: false

# 智能体协作服务配置 - 开发环境简化版
agent_coordination:
  enabled: false
  event_bus:
    type: memory
    connection:
      broker_url: none
      topic_prefix: accessibility
      subscription: accessibility-service

# 观测性服务配置 - 开发环境简化版
observability:
  metrics:
    provider: memory
    endpoint: /metrics
    interval_seconds: 60
    labels:
      environment: development
      version: 0.2.0
  tracing:
    provider: memory
    service_name: accessibility-service
    sample_rate: 0.1
  logging:
    provider: stdout
    structured: true

# 安全与隐私配置 - 开发环境简化版
security:
  encryption:
    enabled: false
  access_control:
    enabled: false

# 容灾备份配置 - 开发环境简化版
resilience:
  backup:
    enabled: false

integration:
  xiaoai_service:
    host: localhost
    port: 50052
    timeout_ms: 5000
    retry: 3
  xiaoke_service:
    host: localhost
    port: 50053
    timeout_ms: 5000
    retry: 3
  laoke_service:
    host: localhost
    port: 50054
    timeout_ms: 5000
    retry: 3
  soer_service:
    host: localhost
    port: 50055
    timeout_ms: 5000
    retry: 3

# 无障碍特性支持级别（可供前端配置使用）
accessibility_levels:
  basic:  # 基础无障碍支持
    - screen_reading
    - voice_assistance
    - high_contrast
    - text_resize
  
  intermediate:  # 中级无障碍支持
    - blind_assistance
    - simplified_content
    - dialect_support
    - tcm_accessibility
  
  advanced:  # 高级无障碍支持
    - sign_language
    - braille_output
    - full_voice_control
    - edge_computing
    - multi_dialect 