version: '3.8'

services:
  user-service:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: suoke/user-service:latest
    ports:
      - "8000:8000"
      - "50051:50051"
    environment:
      - USER_SERVICE_DB_PATH=/data/users.db
      - USER_SERVICE_REST_PORT=8000
      - USER_SERVICE_GRPC_PORT=50051
      - USER_SERVICE_DEBUG=false
    volumes:
      - user_service_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  user_service_data:
    driver: local 