# 医疗知识服务默认配置
service:
  name: med-knowledge-service
  version: 1.0.0
  description: 索克生活APP的医疗知识库服务，提供中西医融合的医疗知识检索和管理

server:
  host: 0.0.0.0
  port: 8075
  debug: false
  workers: 4
  timeout: 60
  cors:
    enabled: true
    origins:
      - "*"

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/med-knowledge-service.log
  max_size: 10485760  # 10MB
  backup_count: 5

# 标准数据库配置
database:
  # 主数据库配置（用于元数据和关系型数据）
  primary:
    type: postgresql
    host: ${DB_HOST:-localhost}
    port: ${DB_PORT:-5432}
    username: ${DB_USER:-postgres}
    password: ${DB_PASS:-postgres}
    database: ${DB_NAME:-med_knowledge}
    
    # 连接池配置
    pool:
      min_size: 5
      max_size: ${DB_POOL_SIZE:-20}
      max_overflow: ${DB_MAX_OVERFLOW:-10}
      timeout: ${DB_POOL_TIMEOUT:-30}
      recycle: ${DB_POOL_RECYCLE:-3600}
      use_lifo: true
      echo: ${DB_ECHO:-false}
    
    # 性能优化参数
    optimization:
      prepared_statement_cache_size: 100
      statement_timeout: 30000
      idle_in_transaction_session_timeout: 60000
      effective_cache_size: "4GB"
      maintenance_work_mem: "64MB"
      max_parallel_workers_per_gather: 2
      enable_partitionwise_join: true
    
    # 连接参数
    options:
      application_name: "med_knowledge_service"
      client_encoding: "UTF8"
      connect_timeout: 10
      keepalives: 1
      keepalives_idle: 60
    
    # 事务隔离级别
    isolation_level: "READ COMMITTED"
  
  # 只读副本配置（用于读写分离）
  replicas:
    enabled: ${DB_REPLICAS_ENABLED:-false}
    strategy: "round_robin"
    nodes:
      - host: ${DB_REPLICA1_HOST}
        port: ${DB_REPLICA1_PORT:-5432}
        username: ${DB_REPLICA1_USER:-postgres}
        password: ${DB_REPLICA1_PASS:-postgres}
        database: ${DB_REPLICA1_NAME:-med_knowledge}
        pool:
          min_size: 2
          max_size: ${DB_REPLICA1_POOL_SIZE:-10}
          max_overflow: 5
          timeout: 20
  
  # MongoDB配置（用于非结构化知识文档存储）
  mongodb:
    uri: ${MONGODB_URI:-mongodb://localhost:27017}
    database: ${MONGODB_DB:-med_knowledge}
    min_pool_size: 5
    max_pool_size: 20
    max_connection_idle_time: 60000
    connect_timeout: 20000
    socket_timeout: 300000
    collections:
      - name: tcm_knowledge
        shard_key: category
      - name: western_medicine
        shard_key: category
      - name: nutrition
        shard_key: category
      - name: herbal_medicine
        shard_key: category
      - name: medical_guidance
        shard_key: category
  
  # 向量数据库配置（用于语义搜索）
  vector:
    type: milvus
    host: ${VECTOR_DB_HOST:-localhost}
    port: ${VECTOR_DB_PORT:-19530}
    collection: ${VECTOR_DB_COLLECTION:-med_knowledge_vectors}
    dimension: 768
    metric_type: "IP"  # 内积相似度
    partition_key: "source"
    replica_number: 1
    index_config:
      index_type: "FLAT"
      metric_type: "IP"
      params: {}
  
  # SQLite配置（用于本地存储）
  sqlite:
    path: ${SQLITE_PATH:-data/local.db}
    journal_mode: "WAL"
    synchronous: "NORMAL"
    busy_timeout: 5000
    cache_size: 2000
    temp_store: "MEMORY"
  
  # 缓存配置
  cache:
    type: redis
    host: ${REDIS_HOST:-localhost}
    port: ${REDIS_PORT:-6379}
    db: ${REDIS_DB:-0}
    password: ${REDIS_PASS}
    ttl: ${REDIS_TTL:-3600}
    key_prefix: "med_knowledge:"
    
    # Redis连接池配置
    pool:
      min_idle: 5
      max_idle: 20
      max_active: 50
      max_wait: 3000
      timeout: 2000
    
    # 本地缓存配置（双层缓存）
    local:
      enabled: true
      max_size: 10000
      ttl: 300
  
  # 监控配置
  monitoring:
    query_timeout_threshold: 1000
    slow_query_log: true
    slow_query_threshold: 500
    connection_stats: true
    query_stats: true

# 知识库配置
knowledge:
  embedding:
    model: text-embedding-3-large
    dimension: 768
    chunk_size: 1000
    chunk_overlap: 200
    batch_size: 32
  
  sources:
    - name: tcm_classics
      type: pdf
      path: data/tcm_classics
      language: zh
      priority: high
    
    - name: western_medicine
      type: structured
      path: data/western_medicine
      language: en
      priority: medium
    
    - name: nutrition_database
      type: structured
      path: data/nutrition
      language: zh
      priority: medium
    
    - name: herbal_medicine
      type: structured
      path: data/herbal_medicine
      language: zh
      priority: high
  
  sync:
    interval: 86400  # 每天同步一次
    incremental: true
    max_workers: 4

# 搜索配置
search:
  hybrid:
    enabled: true
    vector_weight: 0.7
    keyword_weight: 0.3
    max_results: 20
  
  reranker:
    enabled: true
    model: cohere-rerank
    top_n: 5

# 安全配置
security:
  jwt:
    secret: ${JWT_SECRET}
    algorithm: HS256
    expires: 3600  # 1小时
  
  api_keys:
    enabled: true
    header_name: X-API-Key

# 可观测性配置
telemetry:
  tracing:
    enabled: ${TRACING_ENABLED:-false}
    exporter: otlp
    endpoint: ${OTLP_ENDPOINT:-localhost:4317}
    service_name: med-knowledge-service
    environment: ${SERVICE_ENV:-development}
  
  metrics:
    enabled: ${METRICS_ENABLED:-true}
    exporter: prometheus
    endpoint: ${METRICS_ENDPOINT:-localhost:9090}
    export_interval: 15  # 秒 