default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    
    sync_code_signing(
      type: "appstore",
      readonly: true
    )
    
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.suoke.life" => "SuoKe Life App Store"
        }
      }
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci if ENV['CI']
    
    sync_code_signing(
      type: "appstore",
      readonly: true
    )
    
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.suoke.life" => "SuoKe Life App Store"
        }
      }
    )
    
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end
end 