apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: user-service-instrumentation
  namespace: suoke
spec:
  exporter:
    endpoint: http://suoke-collector-collector.monitoring:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  env:
    - name: OTEL_SERVICE_NAME
      value: "user-service"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.namespace=suoke,service.name=user-service,service.version=1.0.0"