# AI Model Service 配置文件示例

# 基本设置
app_name: "AI Model Service"
app_version: "1.0.0"
debug: false

# 服务设置
host: "0.0.0.0"
port: 8080
workers: 1

# Kubernetes配置
kubernetes:
  namespace: "suoke-life"
  config_path: ""  # 留空使用集群内配置
  in_cluster: false
  timeout: 60

# 模型注册表配置
model_registry:
  url: "registry.suoke.life"
  username: ""
  password: ""
  namespace: "suoke"

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
  log_level: "INFO"
  json_logs: false

# 安全配置
security:
  enable_auth: true
  jwt_secret: ""
  api_key: ""
  allowed_origins:
    - "*"

# 模型默认配置
default_model_resources:
  cpu: "1"
  memory: "2Gi"
  nvidia.com/gpu: "0"

default_scaling_config:
  min_replicas: 1
  max_replicas: 5
  target_cpu_utilization: 70

# 推理设置
inference_timeout: 30
max_batch_size: 32

# 预定义模型配置
predefined_models:
  - model_id: "deep_tcm_diagnosis"
    name: "深度中医诊断模型"
    version: "v3.0.1"
    model_type: "tcm_diagnosis"
    framework: "tensorflow"
    repository_url: "https://github.com/suoke-life/laoke-tcm-models"
    docker_image: "suoke/tcm-diagnosis:v3.0.1"
    resource_requirements:
      cpu: "2"
      memory: "8Gi"
      nvidia.com/gpu: "1"
    scaling_config:
      min_replicas: 1
      max_replicas: 5
      target_cpu_utilization: 70
    health_check:
      path: "/health"
      port: 8080
      initial_delay: 30
      period: 10
    environment_variables:
      MODEL_PATH: "/models/tcm_diagnosis"
      BATCH_SIZE: "32"
      GPU_MEMORY_FRACTION: "0.8"
    capabilities:
      - "tcm_diagnosis"
      - "syndrome_differentiation"
      - "prescription_recommendation"

  - model_id: "personalized_treatment"
    name: "个性化治疗方案模型"
    version: "v2.1.0"
    model_type: "multimodal"
    framework: "pytorch"
    repository_url: "https://github.com/suoke-life/treatment-models"
    docker_image: "suoke/treatment-planner:v2.1.0"
    resource_requirements:
      cpu: "4"
      memory: "16Gi"
      nvidia.com/gpu: "2"
    scaling_config:
      min_replicas: 2
      max_replicas: 8
      target_cpu_utilization: 60
    health_check:
      path: "/health"
      port: 8080
      initial_delay: 45
      period: 15
    environment_variables:
      MODEL_PATH: "/models/treatment_planner"
      KNOWLEDGE_BASE_URL: "http://knowledge-service:8080"
    capabilities:
      - "treatment_planning"
      - "drug_interaction"
      - "lifestyle_recommendation" 