# Prometheus 配置文件
# 用于监控索克生活医学知识服务

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'suoke-life'
    service: 'med-knowledge'

# 规则文件
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # 医学知识服务监控
  - job_name: 'med-knowledge'
    static_configs:
      - targets: ['med-knowledge:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Neo4j 数据库监控
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis 缓存监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # 系统监控 (如果有 node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 存储配置在启动参数中设置
# --storage.tsdb.retention.time=15d
# --storage.tsdb.retention.size=10GB 