apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suoke
commonLabels:
  app: agent-coordinator
  part-of: suoke-platform
  managed-by: kustomize
  component: agent-coordinator
resources:
- ../deployment.yaml
- ../service.yaml
- ../service-config.yaml
- ../configmap.yaml
- ../networkpolicy.yaml
- ../pdb.yaml
- ../hpa.yaml
- ../pvc.yaml
images:
- name: agent-coordinator
  newName: suoke-registry.cn-hangzhou.cr.aliyuncs.com/suoke/agent-coordinator-service
  newTag: latest 