apiVersion: apps/v1
kind: Deployment
metadata:
  name: accessibility-service
  namespace: suoke-ai-np
  labels:
    app: accessibility-service
    app.kubernetes.io/part-of: suoke-life
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: accessibility-service
  template:
    metadata:
      labels:
        app: accessibility-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: accessibility-service
        image: ${REGISTRY_URL}/suoke/accessibility-service:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ACCESSIBILITY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accessibility-secrets
              key: db-password
        volumeMounts:
        - name: config
          mountPath: /app/config/config.yaml
          subPath: config.yaml
        - name: logs
          mountPath: /var/log/accessibility-service
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - |
              import socket
              socket.socket().connect(('localhost', 50051))
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - |
              import socket
              socket.socket().connect(('localhost', 50051))
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: config
        configMap:
          name: accessibility-config
      - name: logs
        emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-nodepool: suoke-ai-np
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - accessibility-service
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: accessibility-service
  namespace: suoke-ai-np
  labels:
    app: accessibility-service
    app.kubernetes.io/part-of: suoke-life
spec:
  selector:
    app: accessibility-service
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  - port: 9090
    targetPort: 9090
    name: metrics
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accessibility-config
  namespace: suoke-ai-np
data:
  config.yaml: |
    service:
      name: accessibility-service
      version: 0.1.0
      host: 0.0.0.0
      port: 50051

    models:
      scene_model: microsoft/beit-base-patch16-224-pt22k
      sign_language_model: mediapipe/hands
      speech_model:
        asr: silero-models/silero-stt-model
        tts: silero-models/silero-tts-model
      conversion_model: google/flan-t5-base

    logging:
      level: INFO
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      file: /var/log/accessibility-service/service.log

    database:
      host: postgres.db
      port: 5432
      name: accessibility_db
      user: accessibility_user
      password: ${ACCESSIBILITY_DB_PASSWORD}

    features:
      blind_assistance:
        enabled: true
        max_image_size: 1024
        confidence_threshold: 0.7
        obstacle_detection:
          max_distance: 10
          min_confidence: 0.6

      sign_language:
        enabled: true
        supported_languages:
          - zh-CN
          - en-US
        model_options:
          min_detection_confidence: 0.7
          min_tracking_confidence: 0.5

      screen_reading:
        enabled: true
        element_detection_threshold: 0.6
        ocr_conf_threshold: 0.7
        highlight_elements: true
        auto_scroll: true

      voice_assistance:
        enabled: true
        supported_dialects:
          - mandarin
          - cantonese
          - sichuanese
          - shanghainese
          - hokkien
          - hakka
          - northeastern
          - northwestern
        asr_options:
          sample_rate: 16000
          timeout_seconds: 30

      content_conversion:
        enabled: true
        supported_formats:
          - audio
          - simplified
          - braille
        simplification_level: 2

    integration:
      xiaoai_service:
        host: xiaoai-service
        port: 50052
        timeout_ms: 5000
        retry: 3

      xiaoke_service:
        host: xiaoke-service
        port: 50053
        timeout_ms: 5000
        retry: 3

      laoke_service:
        host: laoke-service
        port: 50054
        timeout_ms: 5000
        retry: 3

      soer_service:
        host: soer-service
        port: 50055
        timeout_ms: 5000
        retry: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: accessibility-service
  namespace: suoke-ai-np
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accessibility-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 120 