apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-service-config
  namespace: suoke
  labels:
    app: rag-service
data:
  vector-db-host: "vector-db-service"
  vector-db-port: "6333"
  vector-db-name: "med_knowledge"
  redis-host: "redis-service"
  redis-port: "6379"
  otlp-endpoint: "otel-collector:4317"
  config.yaml: |
    service:
      name: rag-service
      environment: ${ENV}
      version: ${VERSION}
    
    retriever:
      vector_search:
        enabled: true
        score_threshold: 0.75
        top_k: 5
      keyword_search:
        enabled: true
        score_threshold: 0.6
        top_k: 3
      hybrid:
        enabled: true
        vector_weight: 0.7
        keyword_weight: 0.3
        top_k: 5

    generator:
      model: "gpt-4o"
      temperature: 0.0
      max_tokens: 2000
      context_window: 128000
      prompt_template: |
        你是一位中医专家助手。请基于以下上下文回答用户的问题。
        如果上下文中没有足够信息，请说明你不知道，不要尝试编造信息。
        如果需要提供健康建议，请明确指出这些是一般性建议，用户应该咨询专业医生获取个性化的医疗建议。
        
        上下文：
        {context}
        
        用户问题: {query}

    cache:
      enabled: true
      ttl: 3600
      max_size: 10000

    security:
      rate_limit:
        enabled: true
        requests_per_minute: 60
      
    observability:
      metrics:
        enabled: true
        port: 8000
        path: "/metrics"
      tracing:
        enabled: true
        sample_rate: 0.1
      logging:
        level: "${LOG_LEVEL}"
        format: "json"

    resilience:
      circuit_breaker:
        enabled: true
        failure_threshold: 5
        recovery_timeout: 30
      retry:
        enabled: true
        max_attempts: 3
        initial_backoff: 1
        max_backoff: 10 