[project]
name = "xiaoai-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiodns>=3.2.0,<4.0.0",
    "aiohttp>=3.10.0,<4.0.0",
    "aioprometheus>=23.12.0,<24.0.0",
    "alembic>=1.14.0,<2.0.0",
    "anthropic>=0.40.0,<1.0.0",
    "asyncpg>=0.30.0,<1.0.0",
    "bcrypt>=4.2.0,<5.0.0",
    "black>=24.10.0,<25.0.0",
    "cachetools>=5.5.0,<6.0.0",
    "cryptography>=43.0.0,<44.0.0",
    "fastapi>=0.115.0,<1.0.0",
    "ffmpeg-python>=0.2.0,<1.0.0",
    "flake8>=7.1.0,<8.0.0",
    "grpcio>=1.68.0,<2.0.0",
    "grpcio-health-checking>=1.68.0,<2.0.0",
    "grpcio-reflection>=1.68.0,<2.0.0",
    "grpcio-status>=1.68.0,<2.0.0",
    "grpcio-tools>=1.68.0,<2.0.0",
    "httpx>=0.28.0,<1.0.0",
    "isort>=5.13.0,<6.0.0",
    "jinja2>=3.1.4,<4.0.0",
    "jsonschema>=4.23.0,<5.0.0",
    "langchain>=0.1.0,<1.0.0",
    "langchain>=0.1.0,<1.0.0",
    "langchain>=0.1.0,<1.0.0",
    "librosa>=0.10.2,<1.0.0",
    "loguru>=0.7.2,<1.0.0",
    "matplotlib>=3.9.0,<4.0.0",
    "motor>=3.6.0,<4.0.0",
    "mypy>=1.13.0,<2.0.0",
    "numpy>=2.1.0,<3.0.0",
    "openai>=1.54.0,<2.0.0",
    "opencv-python>=4.10.0,<5.0.0",
    "opentelemetry-api>=1.21.0",
    "opentelemetry-exporter-otlp>=1.21.0",
    "opentelemetry-sdk>=1.21.0",
    "passlib>=1.7.4,<2.0.0",
    "pillow>=11.0.0,<12.0.0",
    "prometheus-client>=0.19.0",
    "protobuf>=5.28.0,<6.0.0",
    "psutil>=6.1.0,<7.0.0",
    "pybreaker>=1.0.2,<2.0.0",
    "pydantic>=2.10.0,<3.0.0",
    "pydantic-settings>=2.6.0,<3.0.0",
    "pydub>=0.25.1,<1.0.0",
    "pyjwt>=2.8.0,<2.9.0",
    "pytest>=8.3.0,<9.0.0",
    "pytest-asyncio>=0.24.0,<1.0.0",
    "pytest-benchmark>=4.0.0,<5.0.0",
    "pytest-cov>=6.0.0,<7.0.0",
    "pytest-mock>=3.14.0,<4.0.0",
    "pytest-xdist>=3.6.0,<4.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "python-json-logger>=2.0.7,<3.0.0",
    "python-multipart>=0.0.12,<1.0.0",
    "pyyaml>=6.0.2,<7.0.0",
    "redis>=5.2.0,<6.0.0",
    "requests>=2.32.0,<3.0.0",
    "scipy>=1.14.0,<2.0.0",
    "sentence-transformers>=3.3.0,<4.0.0",
    "soundfile>=0.12.1,<1.0.0",
    "sphinx>=8.1.0,<9.0.0",
    "sphinx-rtd-theme>=3.0.0,<4.0.0",
    "sqlalchemy>=2.0.36,<3.0.0",
    "statsd>=4.0.1,<5.0.0",
    "tenacity>=9.0.0,<10.0.0",
    "tiktoken>=0.8.0,<1.0.0",
    "torch>=2.1.0,<3.0.0",
    "transformers>=4.36.0,<5.0.0",
    "ujson>=5.10.0,<6.0.0",
    "uvicorn>=0.32.0,<1.0.0",
    "watchdog>=6.0.0,<7.0.0",
    "websockets>=13.1,<14.0",
    "zhipuai>=2.1.0,<3.0.0",
]
