[project]
name = "xiaoai-service"
version = "1.0.0"
description = "xiaoai-service - 索克生活智能体服务"
requires-python = ">=3.11"
dependencies = [
    # 核心Web框架
    "fastapi>=0.115.0,<1.0.0",
    "uvicorn[standard]>=0.32.0,<1.0.0",
    "pydantic>=2.10.0,<3.0.0",
    "pydantic-settings>=2.6.0,<3.0.0",
    
    # 数据库和缓存
    "sqlalchemy>=2.0.36,<3.0.0",
    "asyncpg>=0.30.0,<1.0.0",
    "redis>=5.2.0,<6.0.0",
    
    # HTTP客户端
    "httpx>=0.28.0,<1.0.0",
    "aiohttp>=3.10.0,<4.0.0",
    
    # 配置和日志
    "python-dotenv>=1.0.1,<2.0.0",
    "pyyaml>=6.0.2,<7.0.0",
    "loguru>=0.7.2,<1.0.0",
    
    # 工具库
    "tenacity>=9.0.0,<10.0.0",
    "ujson>=5.10.0,<6.0.0",
    "python-multipart>=0.0.12,<1.0.0",
]

[project.optional-dependencies]
ai = [
    # AI/ML依赖 - 可选安装
    "torch>=2.1.0,<3.0.0",
    "transformers>=4.36.0,<5.0.0",
    "sentence-transformers>=3.3.0,<4.0.0",
    "langchain>=0.1.0,<1.0.0",
    "langchain-core>=0.1.0,<1.0.0",
    "langchain-openai>=0.1.0,<1.0.0",
    "openai>=1.54.0,<2.0.0",
    "anthropic>=0.40.0,<1.0.0",
    "numpy>=2.1.0,<3.0.0",
    "scipy>=1.14.0,<2.0.0",
]

dev = [
    "pytest>=8.3.0,<9.0.0",
    "pytest-asyncio>=0.24.0,<1.0.0",
    "pytest-cov>=6.0.0,<7.0.0",
    "black>=24.10.0,<25.0.0",
    "isort>=5.13.0,<6.0.0",
    "mypy>=1.13.0,<2.0.0",
]

[tool.black]
line-length = 88
target-version = ['py311', 'py312', 'py313']

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = "test_*.py"
asyncio_mode = "auto"
