apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke-dev

bases:
  - ../../base

patchesStrategicMerge:
  - ../../patches/dev-overlay.yaml
  - ../../patches/storage-class-patch.yaml
  - ../../patches/node-selector-patch.yaml

configMapGenerator:
  - name: inquiry-diagnosis-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - OTEL_LOG_LEVEL=debug
      - AI_MODEL_VERSION=dev

images:
  - name: inquiry-diagnosis-service
    newName: suokelife/inquiry-diagnosis-service
    newTag: dev 