apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-logs-pvc
spec:
  storageClassName: alicloud-disk-efficiency
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-config-pvc
spec:
  storageClassName: alicloud-disk-efficiency
  resources:
    requests:
      storage: 1Gi 