apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: looking-diagnosis-backup-pvc
  labels:
    app: looking-diagnosis-service
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: standard
  volumeMode: Filesystem 