apiVersion: v1
kind: ServiceAccount
metadata:
  name: looking-diagnosis-service-account
  namespace: suoke
  labels:
    app: looking-diagnosis
    service: four-diagnosis
  annotations:
    vault.hashicorp.com/role: "looking-diagnosis-service-role" 