apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suoke-auth-service.fullname" . }}-secret
  labels:
    {{- include "suoke-auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
  database-password: {{ .Values.secrets.databasePassword | b64enc }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc }}
  {{- if .Values.config.oauth.google.enabled }}
  oauth-google-client-secret: {{ .Values.secrets.oauthGoogleClientSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.oauth.github.enabled }}
  oauth-github-client-secret: {{ .Values.secrets.oauthGithubClientSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.oauth.wechat.enabled }}
  oauth-wechat-client-secret: {{ .Values.secrets.oauthWechatClientSecret | b64enc }}
  {{- end }} 