apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suoke-dev
resources:
- ../../base

patchesStrategicMerge:
- resources-patch.yaml
- storage-class-patch.yaml

commonLabels:
  environment: development
  tier: backend

namePrefix: dev-

replicas:
- name: agent-coordinator
  count: 1 