apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suoke-dev
resources:
- ../../base

patches:
- path: patches/deployment-patch.yaml
- path: patches/amd64-node-selector.yaml

commonLabels:
  app: agent-coordinator
  environment: dev

images:
  - name: agent-coordinator
    newName: suoke-registry.cn-hangzhou.cr.aliyuncs.com/suoke/agent-coordinator
    newTag: latest

namePrefix: dev-

replicas:
- name: agent-coordinator
  count: 1 