apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-logs-pvc
spec:
  storageClassName: alicloud-disk-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-config-pvc
spec:
  storageClassName: alicloud-disk-ssd