apiVersion: v1
kind: ServiceAccount
metadata:
  name: smell-diagnosis-service-account
  namespace: suoke
  labels:
    app: smell-diagnosis-service
    service: four-diagnosis
  annotations:
    vault.hashicorp.com/role: "smell-diagnosis-service-role" 