apiVersion: v1
kind: Service
metadata:
  name: smell-diagnosis-service
  namespace: suoke
  labels:
    app: smell-diagnosis-service
    service: four-diagnosis
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9464'
    prometheus.io/path: '/metrics'
spec:
  type: ClusterIP
  selector:
    app: smell-diagnosis-service
  ports:
  - port: 3002
    targetPort: http
    protocol: TCP
    name: http
  - port: 9464
    targetPort: metrics
    protocol: TCP
    name: metrics 