apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke-dev

commonLabels:
  environment: development

bases:
  - ../../base

patchesStrategicMerge:
  - resources-patch.yaml

configMapGenerator:
  - name: corn-maze-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DEBUG=true
      - WEBSOCKET_HEARTBEAT_INTERVAL=10000
      - API_PREFIX=/api/corn-maze

images:
  - name: suoke-registry.cn-hangzhou.cr.aliyuncs.com/suoke/corn-maze-service
    newTag: dev 