apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suoke-bench-data-pvc
  namespace: suoke-core
  labels:
    app: suoke-bench-service
    app.kubernetes.io/part-of: suoke-life
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suoke-bench-reports-pvc
  namespace: suoke-core
  labels:
    app: suoke-bench-service
    app.kubernetes.io/part-of: suoke-life
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage