apiVersion: v1
kind: Namespace
metadata:
  name: suoke-bench
  labels:
    name: suoke-bench
    part-of: suoke-life
    component: evaluation

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suoke-bench-config
  namespace: suoke-bench
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8000
      grpc_port: 50051
      workers: 4
      debug: false
    
    storage:
      type: "local"
      local:
        data_dir: "/data"
        results_dir: "/data/results"
        reports_dir: "/data/reports"
    
    metrics:
      default_threshold:
        accuracy: 0.85
        precision: 0.80
        recall: 0.80
        f1: 0.82
        latency_ms: 200
        throughput: 100
    
    logging:
      level: "INFO"
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      file: "/var/log/suoke-bench/service.log"
      max_size: 100
      backup_count: 10
    
    monitoring:
      prometheus:
        enabled: true
        port: 9090
      grafana:
        enabled: true
        port: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: suoke-bench-secrets
  namespace: suoke-bench
type: Opaque
data:
  API_KEY: "c3Vva2UtYmVuY2gtc2VjcmV0LWtleQ=="  # base64 encoded

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suoke-bench-data
  namespace: suoke-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suoke-bench
  namespace: suoke-bench
  labels:
    app: suoke-bench
    part-of: suoke-life
    component: evaluation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suoke-bench
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: suoke-bench
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: suoke-bench
          image: suoke/bench-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 50051
              name: grpc
            - containerPort: 9090
              name: metrics
          env:
            - name: CONFIG_FILE
              value: "/etc/suoke-bench/config.yaml"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: suoke-bench-secrets
                  key: API_KEY
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /etc/suoke-bench
              readOnly: true
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /var/log/suoke-bench
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: suoke-bench-config
        - name: data
          persistentVolumeClaim:
            claimName: suoke-bench-data
        - name: logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: suoke-bench
  namespace: suoke-bench
  labels:
    app: suoke-bench
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: suoke-bench

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suoke-bench
  namespace: suoke-bench
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - bench.suoke.life
      secretName: suoke-bench-tls
  rules:
    - host: bench.suoke.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suoke-bench
                port:
                  name: http

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: suoke-bench
  namespace: suoke-bench
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: suoke-bench
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: suoke-bench
  namespace: suoke-bench
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: suoke-bench
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: suoke-bench
  namespace: suoke-bench
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: suoke-bench 