# Ruff 配置文件
# 针对索克生活无障碍服务的代码检查配置

# 目标Python版本
target-version = "py313"

# 行长度限制
line-length = 88

# 包含的文件类型
include = ["*.py", "*.pyi"]

# 排除的目录
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

[lint]
# 启用的规则集
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]

# 忽略的规则
ignore = [
    "RUF001",  # 忽略中文全角标点符号警告
    "RUF002",  # 忽略docstring中的中文标点符号
    "RUF003",  # 忽略注释中的中文标点符号
    "E501",    # 行长度超限（由black处理）
    "B007",    # 未使用的循环变量（在某些情况下是合理的）
    "F841",    # 未使用的局部变量（在开发阶段可能有用）
]

[lint.per-file-ignores]
# 测试文件的特殊规则
"test_*.py" = ["F401", "F811"]  # 允许测试文件中的未使用导入
"**/test/**/*.py" = ["F401", "F811"]

# 配置文件的特殊规则
"config/*.py" = ["F401"]  # 配置文件可能有未使用的导入

[format]
# 格式化配置
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.isort]
# import排序配置
known-first-party = ["internal", "config"]
force-single-line = false
combine-as-imports = true 