version: '3.8'

services:
  accessibility-service:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    container_name: accessibility-service
    ports:
      - "50051:50051"
      - "9090:9090"
    volumes:
      - ./config:/app/config
      - ./logs:/var/log/accessibility-service
    environment:
      - ACCESSIBILITY_CONFIG_PATH=/app/config/config.yaml
      - ACCESSIBILITY_DB_PASSWORD=dev_password
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket().connect(('localhost', 50051))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - accessibility-net

  accessibility-test-client:
    build:
      context: ./test/client
      dockerfile: Dockerfile
    container_name: accessibility-test-client
    depends_on:
      - accessibility-service
    volumes:
      - ./test/client:/app
      - ./test/data:/app/data
    environment:
      - ACCESSIBILITY_SERVICE_HOST=accessibility-service
      - ACCESSIBILITY_SERVICE_PORT=50051
    networks:
      - accessibility-net
    command: ["tail", "-f", "/dev/null"]  # 保持容器运行，用于执行测试命令

networks:
  accessibility-net:
    driver: bridge 