apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suoke

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- hpa.yaml

configMapGenerator:
- name: rag-service-config
  behavior: merge
  literals:
  - ENV=production
  - VERSION=1.0.0
  - LOG_LEVEL=info
  - vector-db-host=milvus-service.suoke.svc.cluster.local
  - redis-host=redis-master.suoke.svc.cluster.local
  - otlp-endpoint=otel-collector.monitoring.svc.cluster.local:4317

images:
- name: ${DOCKER_REGISTRY}/suoke/rag-service
  newTag: ${TAG}

replicas:
- name: rag-service
  count: 3 