components:
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: 请求参数错误
    InternalError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: 服务器内部错误
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: 未授权访问
  schemas:
    Error:
      properties:
        code:
          type: string
        details:
          type: object
        message:
          type: string
      type: object
    HealthResponse:
      properties:
        checks:
          type: object
        status:
          enum:
          - healthy
          - degraded
          - unhealthy
          type: string
        timestamp:
          format: date-time
          type: string
        uptime_seconds:
          type: integer
        version:
          type: string
      type: object
    Location:
      properties:
        altitude:
          type: number
        latitude:
          type: number
        longitude:
          type: number
      required:
      - latitude
      - longitude
      type: object
    NavigationResponse:
      properties:
        difficulty_level:
          type: string
        estimated_time:
          type: number
        instructions:
          items:
            type: string
          type: array
        timestamp:
          format: date-time
          type: string
        user_id:
          type: string
      type: object
    ObstacleDetectionResponse:
      properties:
        obstacles:
          items:
            properties:
              direction:
                type: string
              distance:
                type: number
              severity:
                enum:
                - low
                - medium
                - high
                type: string
              type:
                type: string
            type: object
          type: array
        safe_path:
          type: object
        timestamp:
          format: date-time
          type: string
        user_id:
          type: string
      type: object
    SceneAnalysisResponse:
      properties:
        navigation_suggestions:
          items:
            type: string
          type: array
        objects:
          items:
            properties:
              confidence:
                type: number
              position:
                type: object
              type:
                type: string
            type: object
          type: array
        scene_description:
          type: string
        timestamp:
          format: date-time
          type: string
        user_id:
          type: string
      type: object
    ScreenReadingResponse:
      properties:
        accessibility_score:
          type: number
        processed_content:
          type: string
        reading_time:
          type: number
        timestamp:
          format: date-time
          type: string
        user_id:
          type: string
      type: object
    SignLanguageResponse:
      properties:
        confidence:
          type: number
        gestures:
          items:
            type: object
          type: array
        recognized_text:
          type: string
        timestamp:
          format: date-time
          type: string
        user_id:
          type: string
      type: object
    SpeechToTextResponse:
      properties:
        confidence:
          type: number
        language:
          type: string
        text:
          type: string
        timestamp:
          format: date-time
          type: string
        user_id:
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: tech@suoke.life
    name: 索克生活技术团队
    url: https://suoke.life
  description: 索克生活无障碍服务API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Accessibility Service
  version: 1.0.0
openapi: 3.0.3
paths:
  /blind-assistance/analyze-scene:
    post:
      description: 分析图像或视频中的场景，识别障碍物和导航信息
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                image:
                  description: 图像文件
                  format: binary
                  type: string
                location:
                  $ref: '#/components/schemas/Location'
                user_id:
                  description: 用户ID
                  type: string
              required:
              - user_id
              - image
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SceneAnalysisResponse'
          description: 场景分析成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      summary: 场景分析
      tags:
      - 导盲服务
  /blind-assistance/detect-obstacles:
    post:
      description: 检测图像中的障碍物并提供导航建议
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                detection_sensitivity:
                  maximum: 1
                  minimum: 0
                  type: number
                image:
                  format: binary
                  type: string
                user_id:
                  type: string
              required:
              - user_id
              - image
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObstacleDetectionResponse'
          description: 障碍物检测成功
      summary: 障碍物检测
      tags:
      - 导盲服务
  /blind-assistance/navigation-guidance:
    post:
      description: 提供基于场景分析的导航指导
      requestBody:
        content:
          application/json:
            schema:
              properties:
                current_location:
                  $ref: '#/components/schemas/Location'
                destination:
                  $ref: '#/components/schemas/Location'
                scene_data:
                  type: object
                user_id:
                  type: string
              required:
              - user_id
              - current_location
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationResponse'
          description: 导航指导成功
      summary: 导航指导
      tags:
      - 导盲服务
  /content-conversion/convert:
    post:
      description: 转换内容格式以提高可访问性
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                accessibility_options:
                  type: object
                file:
                  format: binary
                  type: string
                source_format:
                  type: string
                target_format:
                  type: string
                user_id:
                  type: string
              required:
              - user_id
              - file
              - target_format
              type: object
        required: true
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: 内容转换成功
      summary: 内容格式转换
      tags:
      - 内容转换
  /health:
    get:
      description: 检查服务健康状态
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
          description: 服务健康
      summary: 健康检查
      tags:
      - 系统
  /health/live:
    get:
      description: 检查服务是否存活
      responses:
        '200':
          description: 服务存活
      summary: 存活检查
      tags:
      - 系统
  /health/ready:
    get:
      description: 检查服务是否就绪
      responses:
        '200':
          description: 服务就绪
        '503':
          description: 服务未就绪
      summary: 就绪检查
      tags:
      - 系统
  /screen-reading/read-content:
    post:
      description: 读取并解析屏幕内容
      requestBody:
        content:
          application/json:
            schema:
              properties:
                content:
                  type: string
                content_type:
                  enum:
                  - html
                  - text
                  - pdf
                  type: string
                reading_speed:
                  enum:
                  - slow
                  - normal
                  - fast
                  type: string
                user_id:
                  type: string
              required:
              - user_id
              - content
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenReadingResponse'
          description: 内容阅读成功
      summary: 内容阅读
      tags:
      - 屏幕阅读
  /sign-language/recognize:
    post:
      description: 识别视频中的手语动作并转换为文字
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                language:
                  default: csl
                  type: string
                user_id:
                  type: string
                video:
                  format: binary
                  type: string
              required:
              - user_id
              - video
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignLanguageResponse'
          description: 手语识别成功
      summary: 手语识别
      tags:
      - 手语识别
  /voice-assistance/speech-to-text:
    post:
      description: 将语音音频转换为文字
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                audio:
                  format: binary
                  type: string
                format:
                  enum:
                  - wav
                  - mp3
                  - m4a
                  type: string
                language:
                  default: zh-CN
                  type: string
                user_id:
                  type: string
              required:
              - user_id
              - audio
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeechToTextResponse'
          description: 语音转文字成功
      summary: 语音转文字
      tags:
      - 语音助手
  /voice-assistance/text-to-speech:
    post:
      description: 将文字转换为语音音频
      requestBody:
        content:
          application/json:
            schema:
              properties:
                format:
                  default: mp3
                  enum:
                  - wav
                  - mp3
                  type: string
                speed:
                  default: 1.0
                  maximum: 2.0
                  minimum: 0.5
                  type: number
                text:
                  type: string
                user_id:
                  type: string
                voice:
                  default: female
                  type: string
              required:
              - user_id
              - text
              type: object
        required: true
      responses:
        '200':
          content:
            audio/mpeg:
              schema:
                format: binary
                type: string
          description: 文字转语音成功
      summary: 文字转语音
      tags:
      - 语音助手
security:
- BearerAuth: []
- ApiKeyAuth: []
servers:
- description: 生产环境
  url: https://api.suoke.life/accessibility/v1
- description: 测试环境
  url: https://api-staging.suoke.life/accessibility/v1
