global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# 警报规则配置
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # RAG服务监控
  - job_name: "rag-service"
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ["rag-service:8000"]
        labels:
          service: rag-service
          environment: development

  # Prometheus自监控
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: prometheus

  # Milvus监控
  - job_name: "milvus"
    static_configs:
      - targets: ["milvus-standalone:9091"]
        labels:
          service: milvus

  # Redis监控
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: redis

# 警报配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"] 