apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-base-data-pvc
  namespace: suoke-prod
spec:
  storageClassName: alicloud-disk-essd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-base-logs-pvc
  namespace: suoke-prod
spec:
  storageClassName: alicloud-disk-ssd