apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  default.conf: |-
{{ .Values.config.default.conf | indent 4 }} 