apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suoke-staging
resources:
- ../../base
- ./key-rotation.yaml

patchesStrategicMerge:
- storage-class-patch.yaml
- node-affinity-patch.yaml
- resources-patch.yaml

commonLabels:
  environment: staging
  tier: backend

namePrefix: staging-